/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxStm.h"
#include "Ifx_reg.h"
#include "IfxScuRcu.h"
#include "Ifx_Console.h"
#include "Configuration.h"
#include "ConfigurationIsr.h"
#include "Ifx_Lwip.h"
#include "lwip/apps/lwiperf.h"
#include "lan8651.h"
#include "Bsp.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxCpu_syncEvent cpuSyncEvent = 0;

#if LWIP_TCP
static void
lwiperf_report(void *arg, enum lwiperf_report_type report_type,
  const ip_addr_t* local_addr, u16_t local_port, const ip_addr_t* remote_addr, u16_t remote_port,
  u32_t bytes_transferred, u32_t ms_duration, u32_t bandwidth_kbitpsec)
{
  LWIP_UNUSED_ARG(arg);
  LWIP_UNUSED_ARG(local_addr);
  LWIP_UNUSED_ARG(local_port);

  Ifx_Lwip_printf("IPERF report: type=%d, remote: %s:%d, total bytes: %"U32_F", duration in ms: %"U32_F", kbits/s: %"U32_F"\n",
    (int)report_type, ipaddr_ntoa(remote_addr), (int)remote_port, bytes_transferred, ms_duration, bandwidth_kbitpsec);
}
#endif /* LWIP_TCP */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void core0_main (void)
{
    /* Enable the global interrupts of this CPU */
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event: wait until all CPUs are in CpuX_Main to avoid variables' initialization problems */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    IfxStm_CompareConfig stmCompareConfig;                                  /* STM Configuration declaration                */
    IfxStm_initCompareConfig(&stmCompareConfig);                            /* Initialize a default configuration for STM   */
    stmCompareConfig.triggerPriority     = ISR_PRIORITY_OS_TICK;            /* Priority of the interrupt generated by STM   */
    stmCompareConfig.comparatorInterrupt = IfxStm_ComparatorInterrupt_ir0;  /* Select the request source 0                  */
    stmCompareConfig.ticks               = IFX_CFG_STM_TICKS_PER_MS * 10;   /* First interrupt shall occur after 10 ms      */
    stmCompareConfig.typeOfService       = IfxSrc_Tos_cpu0;                 /* CPU0 serves the interrupts                   */
    IfxStm_initCompare(&MODULE_STM0, &stmCompareConfig);                    /* Initialize the Compare functionality         */

    {
        uint8_t mac[6] = {
            LAN8651_MAC0,
            LAN8651_MAC1,
            LAN8651_MAC2,
            LAN8651_MAC3,
            LAN8651_MAC4,
            LAN8651_MAC5,
        };
        eth_addr_t ethAddr;
        ip_addr_t ipAddr  = IPADDR4_INIT_BYTES(LAN8651_IP_ADDR0, LAN8651_IP_ADDR1, LAN8651_IP_ADDR2, LAN8651_IP_ADDR3);
        ip_addr_t netMask = IPADDR4_INIT_BYTES(LAN8651_NETMASK0, LAN8651_NETMASK1, LAN8651_NETMASK2, LAN8651_NETMASK3);
        ip_addr_t gateway = IPADDR4_INIT_BYTES(LAN8651_GATEWAY0, LAN8651_GATEWAY1, LAN8651_GATEWAY2, LAN8651_GATEWAY3);

        ethAddr.addr[0] = mac[0];
        ethAddr.addr[1] = mac[1];
        ethAddr.addr[2] = mac[2];
        ethAddr.addr[3] = mac[3];
        ethAddr.addr[4] = mac[4];
        ethAddr.addr[5] = mac[5];

        if (lan8651_init(&g_lan8651,
                &MODULE_QSPI2,
                LAN8651_RST_PORT,
                LAN8651_RST_PIN,
                LAN8651_INT_PORT,
                LAN8651_INT_PIN,
                mac) != kLan8651Status_Ok)
        {
            Ifx_Lwip_printf("LAN8651 init failed");
            while (1)
            {
            }
        }

        if (lan8651_start(&g_lan8651) != kLan8651Status_Ok)
        {
            Ifx_Lwip_printf("LAN8651 start failed");
            while (1)
            {
            }
        }

        Ifx_Lwip_init_with_ip(ethAddr, ipAddr, netMask, gateway);
    }

#if LWIP_TCP
    lwiperf_start_tcp_server_default(lwiperf_report, NULL);
#endif

    while (1)
    {
        Ifx_Lwip_pollTimerFlags();                          /* Poll LwIP timers and trigger protocols execution if required */
        Ifx_Lwip_pollReceiveFlags();                        /* Receive data package through ETH                             */
    }
}

IFX_INTERRUPT(ISR_Qspi2_Tx, 0, ISR_PRIORITY_QSPI2_TX);
void ISR_Qspi2_Tx(void)
{
    lan8651_qspi_tx_isr();
}

IFX_INTERRUPT(ISR_Qspi2_Rx, 0, ISR_PRIORITY_QSPI2_RX);
void ISR_Qspi2_Rx(void)
{
    lan8651_qspi_rx_isr();
}

IFX_INTERRUPT(ISR_Qspi2_Er, 0, ISR_PRIORITY_QSPI2_ER);
void ISR_Qspi2_Er(void)
{
    lan8651_qspi_er_isr();
}

/* This interrupt is raised by the STM0 */
IFX_INTERRUPT (updateLwIPStackISR, 0, ISR_PRIORITY_OS_TICK);

/* ISR to update LwIP stack */
void updateLwIPStackISR(void)
{
    /* Configure STM to generate an interrupt in 1 ms */
    IfxStm_increaseCompare(&MODULE_STM0, IfxStm_Comparator_0, IFX_CFG_STM_TICKS_PER_MS);

    g_TickCount_1ms++;                                      /* Increase LwIP system time                                    */

    Ifx_Lwip_onTimerTick();                                 /* Every 1 ms LwIP timers are increased for all the enabled
                                                             * protocols (ARP, TCP, DHCP, LINK)                             */
}
