################################################################################
# \file bsp.mk
#
################################################################################
# \copyright
# Copyright 2018-2023 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.

# Any additional defines to apply when using this board.

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CYT2B95CAE
DEVICE:=CYT2B95CAE
DEVICE_COMPONENTS:=CAT1 CAT1A TVIIBE2M
DEVICE_CYT2B95CAE_CORES:=CORE_NAME_CM0P_0 CORE_NAME_CM4_0
DEVICE_CYT2B95CAE_DIE:=TVIIBE2M
DEVICE_CYT2B95CAE_FEATURES:=CM4_0_FPU_PRESENT
DEVICE_CYT2B95CAE_FLASH_KB:=2112
DEVICE_CYT2B95CAE_IPBLOCKS:=M4CPUSS_VER2 M4CPUSS_VER2_V2 MXCXPI MXCXPI_V1 MXDFT MXDFT_V1 MXEFUSE_VER2 MXEFUSE_VER2_V2 MXEVTGEN MXEVTGEN_V1 MXLIN MXLIN_V1 MXPERI_VER2 MXPERI_VER2_V2 MXS40EPASS MXS40EPASS_V1 MXS40IOSS MXS40IOSS_V2 MXS40SRSS_VER2 MXS40SRSS_VER2_V2 MXSCB_VER2_S40E MXSCB_VER2_S40E_V2 MXTCPWM_VER2 MXTCPWM_VER2_V2 MXTTCANFD MXTTCANFD_V1
DEVICE_CYT2B95CAE_SRAM_KB:=256
DEVICE_LIST:=CYT2B95CAE
DEVICE_TOOL_IDS:=bsp-assistant device-configurator dfuh-tool library-manager project-creator smartio-configurator
RECIPE_DIR:=$(SEARCH_recipe-make-cat1a)
BSP_COMPONENTS:=CM0P_SLEEP
BSP_DEFINES:=CY_USING_HAL
