/* lin12.c — TC397 LIN x11 driver (ASCLIN LIN, polling, single-core).
 *
 * Design notes:
 * - iLLD IfxAsclin_Lin blocking APIs (receiveHeader/receiveResponse/...) loop
 *   forever until HW flags arrive, so they cannot be used for multi-node
 *   scripted tests on one core (master TX while slaves RX would deadlock).
 *   This driver therefore implements its own tick-timeout guarded primitives
 *   on top of the IfxAsclin_* flag helpers, mirroring the iLLD sequences.
 * - Transactions are master-driven and fully synchronous: arm slaves ->
 *   master header -> slaves check header -> arm slaves for response ->
 *   response TX -> receivers check response. Gaps are sub-ms, well inside
 *   the LIN response-space / response-timeout window (DATCON.RESPONSE=255).
 * - Chemistry: PID parity is generated by lin_pid(); HW checks parity on RX
 *   (LP flag) and checksum on response RX (LC flag, enhanced by default).
 */
#include "lin12.h"
#include "IfxAsclin_Lin.h"
#include "IfxAsclin_PinMap.h"
#include "IfxPort.h"
#include <string.h>

extern volatile uint32 g_TickCount_1ms;

linChState_t g_lin[LIN_NUM];
float32 g_linBaud = 19200.0f;

/* ASCLIN SFR per logical LIN (LINn -> MODULE_ASCLINn). LIN0 unused. */
static Ifx_ASCLIN *const linSfr[LIN_NUM] = {
    &MODULE_ASCLIN0, &MODULE_ASCLIN1, &MODULE_ASCLIN2, &MODULE_ASCLIN3,
    &MODULE_ASCLIN4, &MODULE_ASCLIN5, &MODULE_ASCLIN6, &MODULE_ASCLIN7,
    &MODULE_ASCLIN8, &MODULE_ASCLIN9, &MODULE_ASCLIN10, &MODULE_ASCLIN11
};

static IfxAsclin_Lin linHandle[LIN_NUM];

/* Pin pairs, verified against IfxAsclin_PinMap_TC39xB_LFBGA292 (.h/.c).
 * LIN0 entry is a placeholder (never used for init). */
static const IfxAsclin_Lin_Pins linPins[LIN_NUM] = {
    {NULL_PTR, IfxPort_InputMode_pullUp, NULL_PTR, IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN0 placeholder */
    {&IfxAsclin1_RXB_P15_5_IN,  IfxPort_InputMode_pullUp, &IfxAsclin1_TX_P15_4_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN1 */
    {&IfxAsclin2_RXC_P02_10_IN, IfxPort_InputMode_pullUp, &IfxAsclin2_TX_P10_5_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN2 */
    {&IfxAsclin3_RXC_P20_3_IN,  IfxPort_InputMode_pullUp, &IfxAsclin3_TX_P20_0_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN3 */
    {&IfxAsclin4_RXA_P00_12_IN, IfxPort_InputMode_pullUp, &IfxAsclin4_TX_P00_9_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN4 */
    {&IfxAsclin5_RXA_P00_6_IN,  IfxPort_InputMode_pullUp, &IfxAsclin5_TX_P00_7_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN5 */
    {&IfxAsclin6_RXF_P23_1_IN,  IfxPort_InputMode_pullUp, &IfxAsclin6_TX_P23_5_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN6 */
    {&IfxAsclin7_RXF_P22_4_IN,  IfxPort_InputMode_pullUp, &IfxAsclin7_TX_P22_1_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN7 */
    {&IfxAsclin8_RXD_P33_6_IN,  IfxPort_InputMode_pullUp, &IfxAsclin8_TX_P34_5_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN8 */
    {&IfxAsclin9_RXE_P20_6_IN,  IfxPort_InputMode_pullUp, &IfxAsclin9_TX_P01_7_OUT,  IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN9 */
    {&IfxAsclin10_RXA_P00_4_IN, IfxPort_InputMode_pullUp, &IfxAsclin10_TX_P00_8_OUT, IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN10 */
    {&IfxAsclin11_RXD_P21_1_IN, IfxPort_InputMode_pullUp, &IfxAsclin11_TX_P21_0_OUT, IfxPort_OutputMode_pushPull, IfxPort_PadDriver_cmosAutomotiveSpeed1}, /* LIN11 master */
};

/* ---------- TLIN1024 EN (= board SLP_N, high = normal) ---------- */
void lin_xcvr_init(void)
{
    IfxPort_setPinModeOutput(&MODULE_P02, 8, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(&MODULE_P02, 8);    /* LIN0-3 */
    IfxPort_setPinModeOutput(&MODULE_P00, 11, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(&MODULE_P00, 11);   /* LIN4-7 */
    IfxPort_setPinModeOutput(&MODULE_P00, 10, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinHigh(&MODULE_P00, 10);   /* LIN8-11 */
}

void lin_xcvr_set_group(uint8 group, uint8 normal)
{
    IfxPort_State st = normal ? IfxPort_State_high : IfxPort_State_low;
    if (group == 0)      IfxPort_setPinState(&MODULE_P02, 8, st);
    else if (group == 1) IfxPort_setPinState(&MODULE_P00, 11, st);
    else if (group == 2) IfxPort_setPinState(&MODULE_P00, 10, st);
}

void lin_xcvr_set_all(uint8 normal)
{
    lin_xcvr_set_group(0, normal);
    lin_xcvr_set_group(1, normal);
    lin_xcvr_set_group(2, normal);
}

/* ---------- PID helpers ---------- */
uint8 lin_pid(uint8 id6)
{
    uint8 id = id6 & 0x3FU;
    uint8 p0 = ((id >> 0) & 1) ^ ((id >> 1) & 1) ^ ((id >> 2) & 1) ^ ((id >> 4) & 1);
    uint8 p1 = ~(((id >> 1) & 1) ^ ((id >> 3) & 1) ^ ((id >> 4) & 1) ^ ((id >> 5) & 1)) & 1;
    return (uint8)(id | (p0 << 6) | (p1 << 7));
}

uint8 lin_id6(uint8 pid)
{
    return pid & 0x3FU;
}

sint8 lin_pid_check(uint8 pid)
{
    return (lin_pid(pid & 0x3FU) == pid) ? 0 : -1;
}

/* ---------- init ---------- */
static void lin_init_channel(linChannel ch, float32 baud, uint8 isMaster)
{
    IfxAsclin_Lin_Config cfg;
    IfxAsclin_Lin_initModuleConfig(&cfg, linSfr[ch]);
    cfg.linMode = isMaster ? IfxAsclin_LinMode_master : IfxAsclin_LinMode_slave;
    cfg.brg.baudrate = baud;
    /* keep iLLD LIN defaults: prescaler 4 / OS16 / 1 sample / SP3,
     * enhanced checksum, HW checksum on, response timeout 255. */
    cfg.brd.abd = FALSE;
    cfg.pins = &linPins[ch];
    /* RxSel (a..g) == ALTI 0..6: derive from the pin struct itself. */
    cfg.alti = (IfxAsclin_RxInputSelect)linPins[ch].rx->select;
    cfg.isInterruptMode = FALSE;
    IfxAsclin_Lin_initModule(&linHandle[ch], &cfg);

    g_lin[ch].used = 1;
    g_lin[ch].isMaster = isMaster;
}

void lin12_init_all(float32 baud)
{
    linChannel ch;
    if (baud < 1000.0f) baud = 19200.0f;
    g_linBaud = baud;
    memset(g_lin, 0, sizeof(g_lin));
    /* LIN0 intentionally skipped (ASCLIN0 = UART0 debug console). */
    for (ch = LIN1; ch < LIN_NUM; ch++) {
        lin_init_channel(ch, baud, (ch == LIN_MASTER_CH) ? 1 : 0);
    }
}

void lin12_init_all_19200(void)
{
    lin12_init_all(19200.0f);
}

/* ---------- timeout-guarded primitives ---------- */
#define LIN_HDR_TIMEOUT_MS   50u
#define LIN_RESP_TIMEOUT_MS  100u

static uint32 lin_elapsed(uint32 t0)
{
    return g_TickCount_1ms - t0;
}

/* Master/slave header TX (master role): write PID, request header, poll THE. */
static int lin_tx_header(Ifx_ASCLIN *sfr, uint8 pid, linChState_t *st)
{
    uint32 t0;
    uint8 b = pid;
    IfxAsclin_clearAllFlags(sfr);
    IfxAsclin_enableRxFifoInlet(sfr, FALSE);
    IfxAsclin_flushTxFifo(sfr);
    IfxAsclin_enableTxFifoOutlet(sfr, TRUE);
    IfxAsclin_write8(sfr, &b, 1U);
    IfxAsclin_setTransmitHeaderRequestFlag(sfr);
    t0 = g_TickCount_1ms;
    while (!IfxAsclin_getTxHeaderEndFlagStatus(sfr)) {
        if (IfxAsclin_getHeaderTimeoutFlagStatus(sfr) ||
            IfxAsclin_getLinParityErrorFlagStatus(sfr) ||
            IfxAsclin_getFrameErrorFlagStatus(sfr) ||
            IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr)) {
            break;
        }
        if (lin_elapsed(t0) > LIN_HDR_TIMEOUT_MS) break;
    }
    if (IfxAsclin_getTxHeaderEndFlagStatus(sfr)) {
        IfxAsclin_clearTxHeaderEndFlag(sfr);
        if (st) st->txHdr++;
        return 0;
    }
    /* classify */
    if (st) {
        st->hdrErr++;
        if (IfxAsclin_getHeaderTimeoutFlagStatus(sfr)) st->timeoutErr++;
        if (IfxAsclin_getLinParityErrorFlagStatus(sfr)) st->parityErr++;
        if (IfxAsclin_getFrameErrorFlagStatus(sfr) ||
            IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr)) st->frameErr++;
        if (!IfxAsclin_getHeaderTimeoutFlagStatus(sfr) &&
            !IfxAsclin_getLinParityErrorFlagStatus(sfr) &&
            !IfxAsclin_getFrameErrorFlagStatus(sfr) &&
            !IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr)) st->timeoutErr++;
    }
    IfxAsclin_clearAllFlags(sfr);
    return -1;
}

/* Response TX (either role): DATLEN + checksum mode, write data, poll TRE. */
static int lin_tx_response(Ifx_ASCLIN *sfr, const uint8 *data, uint8 len,
                           uint8 classic, linChState_t *st)
{
    uint32 t0;
    if (len < 1) len = 1;
    if (len > 8) len = 8;
    IfxAsclin_setDataLength(sfr, (IfxAsclin_DataLength)(len - 1));
    IfxAsclin_setChecksumMode(sfr, classic ? IfxAsclin_Checksum_classic : IfxAsclin_Checksum_enhanced);
    IfxAsclin_clearAllFlags(sfr);
    IfxAsclin_flushTxFifo(sfr);
    IfxAsclin_enableRxFifoInlet(sfr, FALSE);
    IfxAsclin_enableTxFifoOutlet(sfr, TRUE);
    IfxAsclin_write8(sfr, (uint8 *)data, len);
    IfxAsclin_setTransmitResponseRequestFlag(sfr);
    t0 = g_TickCount_1ms;
    while (!IfxAsclin_getTxResponseEndFlagStatus(sfr)) {
        if (IfxAsclin_getResponseTimeoutFlagStatus(sfr) ||
            IfxAsclin_getTxFifoOverflowFlagStatus(sfr) ||
            IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr) ||
            IfxAsclin_getBreakDetectedFlagStatus(sfr)) {
            break;
        }
        if (lin_elapsed(t0) > LIN_RESP_TIMEOUT_MS) break;
    }
    if (IfxAsclin_getTxResponseEndFlagStatus(sfr)) {
        IfxAsclin_clearTxResponseEndFlag(sfr);
        if (st) st->txResp++;
        return 0;
    }
    if (st) {
        st->respErr++;
        if (IfxAsclin_getResponseTimeoutFlagStatus(sfr)) st->timeoutErr++;
        else if (IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr) ||
                 IfxAsclin_getBreakDetectedFlagStatus(sfr) ||
                 IfxAsclin_getTxFifoOverflowFlagStatus(sfr)) st->frameErr++;
        else st->timeoutErr++;
    }
    IfxAsclin_clearAllFlags(sfr);
    return -1;
}

/* Arm header RX (either role): mirror of IfxAsclin_Lin_prepareHeaderReception. */
static void lin_arm_header(Ifx_ASCLIN *sfr)
{
    IfxAsclin_clearAllFlags(sfr);
    IfxAsclin_flushRxFifo(sfr);
    IfxAsclin_enableTxFifoOutlet(sfr, FALSE);
    IfxAsclin_enableRxFifoInlet(sfr, TRUE);
}

/* Poll header RX with timeout. Returns 0 + pid on success. */
static int lin_poll_header(Ifx_ASCLIN *sfr, uint8 *pid, linChState_t *st)
{
    uint32 t0 = g_TickCount_1ms;
    while (!IfxAsclin_getRxHeaderEndFlagStatus(sfr)) {
        if (IfxAsclin_getHeaderTimeoutFlagStatus(sfr) ||
            IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr) ||
            IfxAsclin_getFrameErrorFlagStatus(sfr) ||
            IfxAsclin_getLinAutoBaudDetectionErrorFlagStatus(sfr) ||
            IfxAsclin_getLinParityErrorFlagStatus(sfr)) {
            break;
        }
        if (lin_elapsed(t0) > LIN_HDR_TIMEOUT_MS) break;
    }
    if (IfxAsclin_getRxHeaderEndFlagStatus(sfr)) {
        uint8 b = 0;
        IfxAsclin_clearRxHeaderEndFlag(sfr);
        IfxAsclin_read8(sfr, &b, 1U);
        if (pid) *pid = b;
        if (st) st->rxHdr++;
        if (st && IfxAsclin_getLinParityErrorFlagStatus(sfr)) {
            /* latched alongside RHE on some revisions: count, keep frame */
            st->parityErr++;
        }
        return 0;
    }
    if (st) {
        st->hdrErr++;
        if (IfxAsclin_getHeaderTimeoutFlagStatus(sfr)) st->timeoutErr++;
        else if (IfxAsclin_getLinParityErrorFlagStatus(sfr)) st->parityErr++;
        else if (IfxAsclin_getFrameErrorFlagStatus(sfr) ||
                 IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr)) st->frameErr++;
        else st->timeoutErr++;
    }
    IfxAsclin_clearAllFlags(sfr);
    return -1;
}

/* Arm response RX: mirror of IfxAsclin_Lin_prepareResponseReception. */
static void lin_arm_response(Ifx_ASCLIN *sfr, uint8 len, uint8 classic)
{
    if (len < 1) len = 1;
    if (len > 8) len = 8;
    IfxAsclin_setDataLength(sfr, (IfxAsclin_DataLength)(len - 1));
    IfxAsclin_setChecksumMode(sfr, classic ? IfxAsclin_Checksum_classic : IfxAsclin_Checksum_enhanced);
    IfxAsclin_clearAllFlags(sfr);
    IfxAsclin_flushRxFifo(sfr);
    IfxAsclin_enableTxFifoOutlet(sfr, FALSE);
    IfxAsclin_enableRxFifoInlet(sfr, TRUE);
}

/* Poll response RX with timeout. Returns 0 + data on success. */
static int lin_poll_response(Ifx_ASCLIN *sfr, uint8 *data, uint8 len,
                             linChState_t *st)
{
    uint32 t0 = g_TickCount_1ms;
    if (len < 1) len = 1;
    if (len > 8) len = 8;
    while (!IfxAsclin_getRxResponseEndFlagStatus(sfr)) {
        if (IfxAsclin_getRxFifoOverflowFlagStatus(sfr) ||
            IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr) ||
            IfxAsclin_getFrameErrorFlagStatus(sfr) ||
            IfxAsclin_getLinChecksumErrorFlagStatus(sfr) ||
            IfxAsclin_getResponseTimeoutFlagStatus(sfr) ||
            IfxAsclin_getBreakDetectedFlagStatus(sfr)) {
            break;
        }
        if (lin_elapsed(t0) > LIN_RESP_TIMEOUT_MS) break;
    }
    if (IfxAsclin_getRxResponseEndFlagStatus(sfr)) {
        IfxAsclin_clearRxResponseEndFlag(sfr);
        IfxAsclin_read8(sfr, data, len);
        if (st) st->rxResp++;
        return 0;
    }
    if (st) {
        st->respErr++;
        if (IfxAsclin_getLinChecksumErrorFlagStatus(sfr)) st->cksumErr++;
        else if (IfxAsclin_getResponseTimeoutFlagStatus(sfr)) st->timeoutErr++;
        else if (IfxAsclin_getFrameErrorFlagStatus(sfr) ||
                 IfxAsclin_getCollisionDetectionErrorFlagStatus(sfr) ||
                 IfxAsclin_getRxFifoOverflowFlagStatus(sfr)) st->frameErr++;
        else st->timeoutErr++;
    }
    IfxAsclin_clearAllFlags(sfr);
    return -1;
}

/* ---------- full transactions ---------- */
int lin_xact_master_tx_mode(uint8 id6, const uint8 *data, uint8 len,
                            uint8 masterClassic, uint8 slaveClassic, uint32 *okMask)
{
    uint8 pid = lin_pid(id6);
    uint8 rxPid;
    uint8 rxData[8];
    linChannel ch;
    int fails = 0;
    uint32 mask = 0;
    int i;

    if (len < 1) len = 1;
    if (len > 8) len = 8;

    /* 1) arm all slaves for header */
    for (ch = LIN1; ch <= LIN10; ch++) lin_arm_header(linSfr[ch]);
    /* 2) master sends header */
    if (lin_tx_header(linSfr[LIN_MASTER_CH], pid, &g_lin[LIN_MASTER_CH]) != 0) {
        /* header itself failed: count all slaves failed */
        for (ch = LIN1; ch <= LIN10; ch++) {
            g_lin[ch].hdrErr++;
            g_lin[ch].timeoutErr++;
        }
        if (okMask) *okMask = 0;
        return 10;
    }
    /* 3) slaves collect header */
    for (ch = LIN1; ch <= LIN10; ch++) {
        if (lin_poll_header(linSfr[ch], &rxPid, &g_lin[ch]) != 0 || rxPid != pid) {
            fails++;
            continue;
        }
        mask |= (1u << ch);
    }
    if (fails) {
        /* still send response so bus settles; receivers ignore result */
        (void)lin_tx_response(linSfr[LIN_MASTER_CH], data, len, masterClassic, NULL);
        if (okMask) *okMask = 0;
        return fails;
    }
    /* 4) arm all slaves for response (slave checksum mode) */
    for (ch = LIN1; ch <= LIN10; ch++) lin_arm_response(linSfr[ch], len, slaveClassic);
    /* 5) master sends response (master checksum mode) */
    if (lin_tx_response(linSfr[LIN_MASTER_CH], data, len, masterClassic, &g_lin[LIN_MASTER_CH]) != 0) {
        for (ch = LIN1; ch <= LIN10; ch++) {
            g_lin[ch].respErr++;
            g_lin[ch].timeoutErr++;
        }
        if (okMask) *okMask = 0;
        return 10;
    }
    /* 6) slaves collect response + verify */
    mask = 0;
    fails = 0;
    for (ch = LIN1; ch <= LIN10; ch++) {
        memset(rxData, 0, sizeof(rxData));
        if (lin_poll_response(linSfr[ch], rxData, len, &g_lin[ch]) != 0) {
            fails++;
            continue;
        }
        for (i = 0; i < len; i++) {
            if (rxData[i] != data[i]) break;
        }
        if (i != len) {
            g_lin[ch].respErr++;
            fails++;
            continue;
        }
        mask |= (1u << ch);
        g_lin[ch].lastId = id6 & 0x3FU;
        g_lin[ch].lastLen = len;
        for (i = 0; i < len; i++) g_lin[ch].lastData[i] = rxData[i];
        g_lin[ch].lastClassic = slaveClassic ? 1 : 0;
        g_lin[ch].lastDir = 0;
        g_lin[ch].lastTick = g_TickCount_1ms;
        g_lin[ch].lastOk = 1;
    }
    g_lin[LIN_MASTER_CH].lastId = id6 & 0x3FU;
    g_lin[LIN_MASTER_CH].lastLen = len;
    for (i = 0; i < len; i++) g_lin[LIN_MASTER_CH].lastData[i] = data[i];
    g_lin[LIN_MASTER_CH].lastClassic = masterClassic ? 1 : 0;
    g_lin[LIN_MASTER_CH].lastDir = 0;
    g_lin[LIN_MASTER_CH].lastTick = g_TickCount_1ms;
    g_lin[LIN_MASTER_CH].lastOk = (fails == 0) ? 1 : 0;
    if (okMask) *okMask = mask;
    return fails;
}

int lin_xact_master_tx(uint8 id6, const uint8 *data, uint8 len, uint8 classic,
                       uint32 *okMask)
{
    return lin_xact_master_tx_mode(id6, data, len, classic, classic, okMask);
}

int lin_xact_slave_tx(uint8 id6, linChannel slave, const uint8 *data, uint8 len,
                      uint8 classic, uint32 *snooped)
{
    uint8 pid = lin_pid(id6);
    uint8 rxPid;
    uint8 rxData[8];
    linChannel ch;
    uint32 snoop = 0;
    int i, rc;

    if (slave < LIN1 || slave > LIN10) return -1;
    if (len < 1) len = 1;
    if (len > 8) len = 8;

    /* 1) arm all slaves for header */
    for (ch = LIN1; ch <= LIN10; ch++) lin_arm_header(linSfr[ch]);
    /* 2) master sends header */
    if (lin_tx_header(linSfr[LIN_MASTER_CH], pid, &g_lin[LIN_MASTER_CH]) != 0) {
        return -1;
    }
    /* 3) slaves collect header */
    for (ch = LIN1; ch <= LIN10; ch++) {
        if (lin_poll_header(linSfr[ch], &rxPid, &g_lin[ch]) != 0 || rxPid != pid) {
            if (ch == slave) return -1;
        }
    }
    /* 4) arm master + snooping slaves for response BEFORE the talker sends */
    lin_arm_response(linSfr[LIN_MASTER_CH], len, classic);
    for (ch = LIN1; ch <= LIN10; ch++) {
        if (ch != slave) lin_arm_response(linSfr[ch], len, classic);
    }
    /* 5) designated slave sends response */
    if (lin_tx_response(linSfr[slave], data, len, classic, &g_lin[slave]) != 0) {
        IfxAsclin_clearAllFlags(linSfr[LIN_MASTER_CH]);
        return -1;
    }
    /* 6) master collects response */
    memset(rxData, 0, sizeof(rxData));
    rc = lin_poll_response(linSfr[LIN_MASTER_CH], rxData, len, &g_lin[LIN_MASTER_CH]);
    if (rc != 0) {
        return -1;
    }
    for (i = 0; i < len; i++) {
        if (rxData[i] != data[i]) return -1;
    }
    /* 7) snoopers collect the same response */
    for (ch = LIN1; ch <= LIN10; ch++) {
        uint8 sb[8];
        int k;
        if (ch == slave) continue;
        memset(sb, 0, sizeof(sb));
        if (lin_poll_response(linSfr[ch], sb, len, &g_lin[ch]) != 0) continue;
        for (k = 0; k < len; k++) {
            if (sb[k] != data[k]) break;
        }
        if (k != len) {
            g_lin[ch].respErr++;
            continue;
        }
        snoop++;
        g_lin[ch].lastId = id6 & 0x3FU;
        g_lin[ch].lastLen = len;
        for (k = 0; k < len; k++) g_lin[ch].lastData[k] = sb[k];
        g_lin[ch].lastClassic = classic ? 1 : 0;
        g_lin[ch].lastDir = 1;
        g_lin[ch].lastTick = g_TickCount_1ms;
        g_lin[ch].lastOk = 1;
    }
    g_lin[slave].lastId = id6 & 0x3FU;
    g_lin[slave].lastLen = len;
    for (i = 0; i < len; i++) g_lin[slave].lastData[i] = data[i];
    g_lin[slave].lastClassic = classic ? 1 : 0;
    g_lin[slave].lastDir = 1;
    g_lin[slave].lastTick = g_TickCount_1ms;
    g_lin[slave].lastOk = 1;
    g_lin[LIN_MASTER_CH].lastId = id6 & 0x3FU;
    g_lin[LIN_MASTER_CH].lastLen = len;
    for (i = 0; i < len; i++) g_lin[LIN_MASTER_CH].lastData[i] = rxData[i];
    g_lin[LIN_MASTER_CH].lastClassic = classic ? 1 : 0;
    g_lin[LIN_MASTER_CH].lastDir = 1;
    g_lin[LIN_MASTER_CH].lastTick = g_TickCount_1ms;
    g_lin[LIN_MASTER_CH].lastOk = 1;
    if (snooped) *snooped = snoop;
    return 0;
}

/* ---------- raw primitives for error-injection tests ---------- */
int lin_raw_master_header(uint8 pid)
{
    return lin_tx_header(linSfr[LIN_MASTER_CH], pid, &g_lin[LIN_MASTER_CH]);
}

int lin_raw_master_response(const uint8 *data, uint8 len, uint8 classic)
{
    if (len < 1) len = 1;
    if (len > 8) len = 8;
    return lin_tx_response(linSfr[LIN_MASTER_CH], data, len, classic, &g_lin[LIN_MASTER_CH]);
}

void lin_slave_arm_header(linChannel ch)
{
    if (ch < LIN1 || ch > LIN10) return;
    lin_arm_header(linSfr[ch]);
}

int lin_slave_poll_header(linChannel ch, uint8 *pid)
{
    if (ch < LIN1 || ch > LIN10) return -1;
    return lin_poll_header(linSfr[ch], pid, &g_lin[ch]);
}

void lin_master_arm_response(uint8 len, uint8 classic)
{
    lin_arm_response(linSfr[LIN_MASTER_CH], len, classic);
}

int lin_master_poll_response(uint8 *data, uint8 len)
{
    return lin_poll_response(linSfr[LIN_MASTER_CH], data, len, &g_lin[LIN_MASTER_CH]);
}
