/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "Ifx_Cfg.h"
#include "IfxCpu.h"
#include "IfxWtu.h"
#include <stdio.h>

#include "serialio.h"

#define UART_BAUDRATE 115200
#define UART_LINE_BUFFER_SIZE 128

static void printStartupBanner(void)
{
    printf("\r\n");
    printf("************************************\r\n");
    printf("*     TC4D7 UART0 printf / echo    *\r\n");
    printf("* Date: %10s                *\r\n", __DATE__);
    printf("************************************\r\n");
    printf("UART0 TX=P14.0 RX=P14.1, 115200-8-N-1\r\n");
    printf("Input a line and press Enter to echo it.\r\n");
}


void core0_main(void)
{
    char lineBuffer[UART_LINE_BUFFER_SIZE];
    uint32 lineLength = 0;
    boolean lastWasCarriageReturn = FALSE;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());

    SERIALIO_Init(UART_BAUDRATE);
    printStartupBanner();
    
    while (1)
    {
        uint8 receivedByte;

        if (!SERIALIO_TryReadByte(&receivedByte))
        {
            continue;
        }

        if ((receivedByte == '\n') && lastWasCarriageReturn)
        {
            lastWasCarriageReturn = FALSE;
            continue;
        }

        if ((receivedByte == '\r') || (receivedByte == '\n'))
        {
            lineBuffer[lineLength] = '\0';
            printf("%s\r\n", lineBuffer);
            lineLength = 0;
            lastWasCarriageReturn = (receivedByte == '\r');
            continue;
        }

        lastWasCarriageReturn = FALSE;

        if (lineLength < (UART_LINE_BUFFER_SIZE - 1U))
        {
            lineBuffer[lineLength++] = (char)receivedByte;
        }
    }
}
