/**
 * \file netif.c
 * \brief Source file of lwIP low level and netif functions
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

/*
 * Copyright (c) 2001-2004 Swedish Institute of Computer Science.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * This file is part of the lwIP TCP/IP stack.
 *
 * Author: Adam Dunkels <adam@sics.se>
 *
 */

/**
 * This file is a skeleton for developing Ethernet network interface
 * drivers for lwIP. Add code to the low_level functions and do a
 * search-and-replace for the word "ethernetif" to replace it with
 * something that better describes your network interface.
 */

#include "lwip/opt.h"

#include <stdio.h>
#include <string.h>

#include "lwip/def.h"
#include "lwip/mem.h"
#include "lwip/pbuf.h"
#include <lwip/stats.h>
#include <lwip/snmp.h>
#include "netif/etharp.h"
#include "netif/ppp/pppoe.h"

#include "Clock/Std/IfxClock.h"
#include "Pms/Std/IfxPmsEvr.h"
#include "Port/Std/IfxPort.h"
#include "Vmt/Std/IfxVmt.h"

#include "Configuration.h"
#include "IfxGeth_Eth.h"
#include "Ifx_Lwip.h"
#include "Ifx_Netif.h"
#include "kit_tc4d7_lite.h"
#include "pdl/ifx_geth.h"
#include "pdl/ifx_hsphy.h"
#include "phy/dp83825i.h"

/* Define those to better describe your network interface. */
#define IFNAME0 'e'
#define IFNAME1 'n'

/**
 * Helper struct to hold private data used to operate your ethernet interface.
 * Keeping the ethernet address of the MAC in this struct is not necessary
 * as it is already kept in the struct netif.
 * But this is only an example, anyway...
 */
struct ethernetif
{
    eth_addr_t *ethaddr;
    /* Add whatever per-interface state that is needed here. */
};

static phy_t g_phy;
static boolean g_netifLinkLogged;
static uint32 g_netifRxFrameCount;
static uint32 g_netifTxFrameCount;

static const Ifx_GETH_MDIO_Pins g_gethMdioPins = {
    .mdc = &BOARD_GETH0_P0_MDC,
    .mdio = &BOARD_GETH0_P0_MDIO,
};

static const IfxHsphy_Geth_RmiiPins g_gethRmiiPins = {
    .rxd0 = &BOARD_GETH0_P0_RXD0,
    .rxd1 = &BOARD_GETH0_P0_RXD1,
    .crsDiv = &BOARD_GETH0_P0_CSRDV,
    .refClk = &BOARD_GETH0_P0_REFCLK,
    .txd0 = &BOARD_GETH0_P0_TXD0,
    .txd1 = &BOARD_GETH0_P0_TXD1,
    .txEn = &BOARD_GETH0_P0_TXEN,
};

#define IFX_NETIF_MDIO_CMD_READ  VAL2FLD(IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_CONTROL_DATA_CMD, 3)
#define IFX_NETIF_MDIO_CMD_WRITE VAL2FLD(IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_CONTROL_DATA_CMD, 1)
#define IFX_NETIF_MDIO_CMD_BUSY  GENMASK(IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_CONTROL_DATA_SBUSY)

static sint32 ifxNetifMdioInit(const Ifx_GETH_MDIO_Pins *pins, uint32 csrClockRate)
{
    uint32 divider;

    MODULE_GETH0.MACEN.U |= 1U << IFX_LWIP_GETH_PORT_INDEX;

    if ((csrClockRate >= 40000000U) && (csrClockRate <= 50000000U))
    {
        divider = 5U;
    }
    else if (csrClockRate >= 350000000U)
    {
        divider = 4U;
    }
    else if (csrClockRate >= 300000000U)
    {
        divider = 3U;
    }
    else if (csrClockRate >= 250000000U)
    {
        divider = 2U;
    }
    else if (csrClockRate >= 150000000U)
    {
        divider = 1U;
    }
    else if (csrClockRate >= 100000000U)
    {
        divider = 0U;
    }
    else
    {
        return -1;
    }

    if (pins != NULL_PTR)
    {
        IfxPort_setPinModeInput(pins->mdio->pin.port, pins->mdio->pin.pinIndex, IfxPort_InputMode_noPullDevice);
        IfxPort_setPinPadDriver(pins->mdio->pin.port, pins->mdio->pin.pinIndex, IfxPort_PadDriver_cmosAutomotiveSpeed3);
        IfxPort_setPinModeOutput(pins->mdc->pin.port, pins->mdc->pin.pinIndex, IfxPort_OutputMode_pushPull, pins->mdc->select);
        IfxPort_setPinPadDriver(pins->mdc->pin.port, pins->mdc->pin.pinIndex, IfxPort_PadDriver_cmosAutomotiveSpeed3);
    }

    MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.U =
        VAL2FLD(IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_CONTROL_DATA_CR, divider);

    return 0;
}

static uint16 ifxNetifMdioRead(uint8 phyAddr, uint8 devAddr, uint16 regAddr)
{
    uint32 commandAddr;
    uint32 commandData;

    (void)devAddr;

    while (MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.B.SBUSY)
    {
    }

    MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.CLAUSE_22_PORT.U |= BIT(phyAddr);

    commandAddr = ((uint32)phyAddr << IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_ADDRESS_PA_OFF) |
                  (((uint32)regAddr & 0x1FU) << IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_ADDRESS_RA_OFF);

    commandData = MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.U &
                  (uint32)~GENMASK(IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_CONTROL_DATA_CMD);

    commandData |= IFX_NETIF_MDIO_CMD_READ | IFX_NETIF_MDIO_CMD_BUSY;

    MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_ADDRESS.U = commandAddr;
    MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.U = commandData;

    while (MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.B.SBUSY)
    {
    }

    return (uint16)MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.B.SDATA;
}

static void ifxNetifMdioWrite(uint8 phyAddr, uint8 devAddr, uint16 regAddr, uint16 regValue)
{
    uint32 commandAddr;
    uint32 commandData;

    (void)devAddr;

    while (MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.B.SBUSY)
    {
    }

    MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.CLAUSE_22_PORT.U |= BIT(phyAddr);

    commandAddr = ((uint32)phyAddr << IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_ADDRESS_PA_OFF) |
                  (((uint32)regAddr & 0x1FU) << IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_ADDRESS_RA_OFF);

    commandData = MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.U &
                  ((uint32)~GENMASK(IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_CONTROL_DATA_CMD) &
                   (uint32)~GENMASK(IFX_GETH_PORT_CORE_MDIO_SINGLE_COMMAND_CONTROL_DATA_SDATA));

    commandData |= IFX_NETIF_MDIO_CMD_WRITE | IFX_NETIF_MDIO_CMD_BUSY | regValue;

    MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_ADDRESS.U = commandAddr;
    MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.U = commandData;

    while (MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MDIO.SINGLE_COMMAND_CONTROL_DATA.B.SBUSY)
    {
    }
}

static void ifxNetifEnableVoltageRails(void)
{
    IfxPmsEvr_enableVoltageRail(&MODULE_PMS, IfxPmsEvr_PrimaryMonitorVoltageSource_vddphphy0);
    IfxPmsEvr_enableVoltageRail(&MODULE_PMS, IfxPmsEvr_PrimaryMonitorVoltageSource_vddphy0);
    IfxPmsEvr_enableVoltageRail(&MODULE_PMS, IfxPmsEvr_PrimaryMonitorVoltageSource_vddphphy1);
    IfxPmsEvr_enableVoltageRail(&MODULE_PMS, IfxPmsEvr_PrimaryMonitorVoltageSource_vddphy1);
    IfxPmsEvr_enableVoltageRail(&MODULE_PMS, IfxPmsEvr_PrimaryMonitorVoltageSource_vddphphy2);
    IfxPmsEvr_enableVoltageRail(&MODULE_PMS, IfxPmsEvr_PrimaryMonitorVoltageSource_vddphy2);
    IfxPmsEvr_enableVoltageRail(&MODULE_PMS, IfxPmsEvr_PrimaryMonitorVoltageSource_vddhsif);
}

static void ifxNetifClearGethSram(void)
{
    printf("ETH init: skip VMT SRAM clear due AXI MBIST stall.\r\n");
}

static void ifxNetifApplyLinkState(netif_t *netif)
{
    Ifx_GETH *geth = &MODULE_GETH0;

    if (g_phy.link_status.is_up == false)
    {
        IfxGeth_stopRx(geth, IFX_LWIP_GETH_PORT_INDEX);
        IfxGeth_stopTx(geth, IFX_LWIP_GETH_PORT_INDEX);
        netif_set_link_down(netif);

        if (g_netifLinkLogged != FALSE)
        {
            g_netifLinkLogged = FALSE;
            printf("ETH link down.\r\n");
        }

        return;
    }

    if (PHY_LINK_IS_SPEED_100M(g_phy.link_status.speed) != 0)
    {
        IfxGeth_setSpeed(geth, IFX_LWIP_GETH_PORT_INDEX, IfxGeth_Speed_100M_MII);
    }
    else
    {
        IfxGeth_setSpeed(geth, IFX_LWIP_GETH_PORT_INDEX, IfxGeth_Speed_10M_MII);
    }

    if (PHY_LINK_IS_FULL_DUPLEX(g_phy.link_status.speed) != 0)
    {
        IfxGeth_setDuplexMode(geth, IFX_LWIP_GETH_PORT_INDEX, IfxGeth_DuplexMode_fullDuplex);
    }
    else
    {
        IfxGeth_setDuplexMode(geth, IFX_LWIP_GETH_PORT_INDEX, IfxGeth_DuplexMode_halfDuplex);
    }

    IfxGeth_startRx(geth, IFX_LWIP_GETH_PORT_INDEX);
    IfxGeth_startTx(geth, IFX_LWIP_GETH_PORT_INDEX);
    netif_set_link_up(netif);

    if (g_netifLinkLogged == FALSE)
    {
        g_netifLinkLogged = TRUE;
        printf("ETH link up: %s %s duplex.\r\n",
               PHY_LINK_IS_SPEED_100M(g_phy.link_status.speed) != 0 ? "100M" : "10M",
               PHY_LINK_IS_FULL_DUPLEX(g_phy.link_status.speed) != 0 ? "full" : "half");
    }
}

/**
 * In this function, the hardware should be initialized.
 * Called from ethernetif_init().
 *
 * @param netif the already initialized lwip network interface structure
 *        for this ethernetif
 */
static void low_level_init(netif_t *netif)
{
    IfxGeth_Eth *ethernetif = netif->state;
    int i;
    IfxGeth_Eth_Config gethConfig;
    const Ifx_HSPHY_ETH_Bits hsphyConfig = {
        .EPR = HSPHY_ETH_EPR_RMII,
        .MDIOEN = TRUE,
        .MDIO = BOARD_GETH0_P0_MDIO.inSelect
    };
    uint32 gethClockRate;

    /* set MAC hardware address length */
    netif->hwaddr_len = ETHARP_HWADDR_LEN;

    /* set MAC hardware address */
    for (i = 0; i < ETHARP_HWADDR_LEN; i++)
    {
        netif->hwaddr[i] = g_Lwip.eth_addr.addr[i];
    }

    /* maximum transfer unit */
    netif->mtu = 1500;

    /* device capabilities */
    /* don't set NETIF_FLAG_ETHARP if this device is not an ethernet one */
    /* we don't set the LINK_UP flag because we don't say when it is linked */
    netif->flags = NETIF_FLAG_BROADCAST | NETIF_FLAG_ETHARP | NETIF_FLAG_ETHERNET;

    printf("ETH init: enable rails...\r\n");
    ifxNetifEnableVoltageRails();

    printf("ETH init: HSPHY...\r\n");
    (void)HSPHY_Init();
    (void)HSPHY_ETH_Init(0U, hsphyConfig);

    printf("ETH init: GETH/MDIO...\r\n");
    IfxGeth_enableModule(&MODULE_GETH0);
    gethClockRate = IfxClock_getXGeth0Frequency();
    (void)ifxNetifMdioInit(&g_gethMdioPins, gethClockRate);

    if (dp83825i_init(&g_phy, IFX_LWIP_GETH_PHY_ADDR, ifxNetifMdioRead, ifxNetifMdioWrite, 0U) != 0)
    {
        printf("ETH init: PHY probe failed at address %u.\r\n", (unsigned)IFX_LWIP_GETH_PHY_ADDR);
        return;
    }

    printf("ETH init: PHY configure...\r\n");
    (void)dp83825i_cfg_link(&g_phy,
                            (enum phy_link_speed)(LINK_HALF_10BASE_T |
                                                  LINK_FULL_10BASE_T |
                                                  LINK_HALF_100BASE_T |
                                                  LINK_FULL_100BASE_T));

    printf("ETH init: clear SRAM...\r\n");
    ifxNetifClearGethSram();

    printf("ETH init: setup RMII input...\r\n");
    IfxHsphy_Geth_setupRmiiInputPins(&MODULE_HSPHY, IfxHsphy_EthIndex_0, &g_gethRmiiPins);
    printf("ETH init: RMII input ready.\r\n");

    printf("ETH init: configure MAC/DMA...\r\n");
    IfxGeth_Eth_initModuleConfig(&gethConfig, &MODULE_GETH0);
    gethConfig.port[0].phyInterfaceMode = IfxGeth_PhyInterfaceMode_rmii_100;
    gethConfig.port[0].mac.disableCrcCheck = FALSE;
    gethConfig.port[0].mtl.rxQueue[0].enable = TRUE;
    gethConfig.port[0].mtl.rxQueue[0].enableDynamicDmaChannelMap = TRUE;
    gethConfig.port[0].mtl.rxQueue[0].rxQueueSize = (4096U >> 8) - 1U;
    gethConfig.port[0].mtl.txQueue[0].enable = TRUE;
    gethConfig.port[0].mtl.txQueue[0].txQueueSize = (4096U >> 8) - 1U;
    memcpy(gethConfig.port[0].mac.macAddress, netif->hwaddr, ETHARP_HWADDR_LEN);

    gethConfig.dma.addressAlignedBeatsEnabled = TRUE;
    gethConfig.dma.burstLength = IfxGeth_DmaBurstLength_16;
    gethConfig.dma.undefinedBurstLength = FALSE;
    memset(gethConfig.dma.burstLengthMultiplierEnable, FALSE, sizeof(gethConfig.dma.burstLengthMultiplierEnable));
    gethConfig.dma.txChannel[0].channelEnable = TRUE;
    gethConfig.dma.txChannel[0].maxBurstLength = IfxGeth_TxBurstLength_16;
    gethConfig.dma.txChannel[0].txDescrList = &IfxGeth_Eth_txDescrList[0][0];
    gethConfig.dma.txChannel[0].txBuffer1Size = IFXGETH_MAX_TX_BUFFER_SIZE;
    gethConfig.dma.txChannel[0].txBuffer1StartAddress = (uint32 *)&channel0TxBuffer1[0][0];
    gethConfig.dma.rxChannel[0].channelEnable = TRUE;
    gethConfig.dma.rxChannel[0].maxBurstLength = IfxGeth_RxBurstLength_16;
    gethConfig.dma.rxChannel[0].rxDescrList = &IfxGeth_Eth_rxDescrList[0][0];
    gethConfig.dma.rxChannel[0].rxBuffer1Size = IFXGETH_MAX_RX_BUFFER_SIZE;
    gethConfig.dma.rxChannel[0].rxBuffer1StartAddress = (uint32 *)&channel0RxBuffer1[0][0];
    gethConfig.bridge.mode = IfxGeth_BridgePortMode_singlePort0;

    printf("ETH init: start module...\r\n");
    IfxGeth_Eth_initModule(ethernetif, &gethConfig);
    (void)ifxNetifMdioInit(NULL_PTR, gethClockRate);
    MODULE_GETH0.PORT[IFX_LWIP_GETH_PORT_INDEX].CORE.MAC_PACKET_FILTER.U = 0U;
    IfxGeth_startRxDma(&MODULE_GETH0, IfxGeth_RxDmaChannel_0);
    IfxGeth_startTxDma(&MODULE_GETH0, IfxGeth_TxDmaChannel_0);
    IfxHsphy_Geth_setupRmiiOutputPins(&MODULE_HSPHY, &g_gethRmiiPins);

    printf("ETH init: initial link check...\r\n");
    ifx_netif_update_link(netif);
    printf("ETH init: complete.\r\n");
}

/**
 * This function should do the actual transmission of the packet. The packet is
 * contained in the pbuf that is passed to the function. This pbuf
 * might be chained.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @param p the MAC packet to send (e.g. IP packet including MAC addresses and type)
 * @return ERR_OK if the packet could be sent
 *         an err_t value if the packet couldn't be sent
 *
 * @note Returning ERR_MEM here if a DMA queue of your MAC is full can lead to
 *       strange results. You might consider waiting for space in the DMA queue
 *       to become availale since the stack doesn't retry to send a packet
 *       dropped because of memory failure (except for the TCP timers).
 */
static err_t low_level_output(netif_t *netif, pbuf_t *p)
{
    IfxGeth_Eth *ethernetif = netif->state;
    struct pbuf *q;
    u8_t *txBuffer;
    u16_t copiedLength = 0U;

#if ETH_PAD_SIZE
    pbuf_header(p, -ETH_PAD_SIZE); /* drop the padding word */
#endif

    txBuffer = IfxGeth_Eth_waitTransmitBuffer(ethernetif, IfxGeth_TxDmaChannel_0);

    for (q = p; q != NULL; q = q->next)
    {
        memcpy(&txBuffer[copiedLength], q->payload, q->len);
        copiedLength = (u16_t)(copiedLength + q->len);
    }

    LWIP_ASSERT("low_level_output length exceeds tx buffer", copiedLength <= IFXGETH_MAX_TX_BUFFER_SIZE);
    IfxGeth_Eth_sendTransmitBuffer(ethernetif, IFX_LWIP_GETH_PORT_INDEX, copiedLength, IfxGeth_TxDmaChannel_0);

#if ETH_PAD_SIZE
    pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif

    LINK_STATS_INC(link.xmit);

    g_netifTxFrameCount += 1U;

    if ((g_netifTxFrameCount <= 4U) || ((g_netifTxFrameCount % 16U) == 0U))
    {
        printf("ETH TX frame #%lu, %u bytes.\r\n", (unsigned long)g_netifTxFrameCount, copiedLength);
    }

    return ERR_OK;
}

static uint16 GetRxFrameSize(IfxGeth_RxDescr *descr)
{
  uint16 len;

  uint32 rdes3 = descr->RDES3.U;
  uint32 rdes1 = descr->RDES1.U;

  if (((rdes3 & (1UL << 15)) != 0U) ||
      ((rdes1 & (1UL << 7)) != 0U) ||
      ((rdes3 & (1UL << 28)) == 0U))
  {
    /* Error, this block is invalid */
    len = 0xFFFFU;
  }
  else
  {
    /* Subtract CRC */
    len = (uint16)((rdes3 & 0x7FFF) - 4U);
  }

  return len;
}

/**
 * Should allocate a pbuf and transfer the bytes of the incoming
 * packet from the interface into the pbuf.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return a pbuf filled with the received packet (including MAC header)
 *         NULL on memory error
 */
static pbuf_t *low_level_input(netif_t *netif)
{
    IfxGeth_Eth *ethernetif = netif->state;
    pbuf_t *p, *q;
    u16_t   len;

    len = 0;
    if (IfxGeth_Eth_isRxDataAvailable(ethernetif, IfxGeth_RxDmaChannel_0) != FALSE)
    {
        len = GetRxFrameSize((IfxGeth_RxDescr *)IfxGeth_Eth_getActualRxDescriptor(ethernetif, IfxGeth_RxDmaChannel_0));

        if (len == 0xFFFFU)
        {
            printf("ETH RX descriptor error, dropping frame.\r\n");
            IfxGeth_Eth_freeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);
            return (pbuf_t *)0;
        }
    }

    if (len == 0)
    {
        return (pbuf_t *)0;
    }

#if ETH_PAD_SIZE
    len += ETH_PAD_SIZE; /* allow room for Ethernet padding */
#endif

    /* We allocate a pbuf chain of pbufs from the pool. */
    p = pbuf_alloc(PBUF_RAW, len, PBUF_POOL);

    if (p != NULL)
    {
#if ETH_PAD_SIZE
        pbuf_header(p, -ETH_PAD_SIZE); /* drop the padding word */
#endif

        u8_t *src = IfxGeth_Eth_getReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);

        /* We iterate over the pbuf chain until we have read the entire
         * packet into the pbuf. */
        for (q = p; q != NULL; q = q->next)
        {
            /* Read enough bytes to fill this pbuf in the chain. The
             * available data in the pbuf is given by the q->len
             * variable.
             * This does not necessarily have to be a memcpy, you can also preallocate
             * pbufs for a DMA-enabled MAC and after receiving truncate it to the
             * actually received size. In this case, ensure the tot_len member of the
             * pbuf is the sum of the chained pbuf len members.
             */
            //read data into(q->payload, q->len);
            memcpy(q->payload, src, q->len);
            src = &src[q->len];

            LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_input: payload=0x%x, len=%d\n", q->payload, q->len));
        }

        IfxGeth_Eth_freeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);

#if ETH_PAD_SIZE
        pbuf_header(p, ETH_PAD_SIZE); /* reclaim the padding word */
#endif

        LINK_STATS_INC(link.recv);
        g_netifRxFrameCount += 1U;

        if ((g_netifRxFrameCount <= 4U) || ((g_netifRxFrameCount % 16U) == 0U))
        {
            printf("ETH RX frame #%lu, %u bytes.\r\n", (unsigned long)g_netifRxFrameCount, len);
        }
    }
    else
    {
        LINK_STATS_INC(link.memerr);
        LINK_STATS_INC(link.drop);
    }

    return p;
}


/**
 * This function should be called when a packet is ready to be read
 * from the interface. It uses the function low_level_input() that
 * should handle the actual reception of bytes from the network
 * interface. Then the type of the received packet is determined and
 * the appropriate input function is called.
 *
 * @param netif the lwip network interface structure for this ethernetif
 */
err_t ifx_netif_input(netif_t *netif)
{
    eth_hdr_t *ethhdr;
    pbuf_t    *p;

    /* move received packet into a new pbuf */
    p = low_level_input(netif);

    /* no packet could be read, silently ignore this */
    if (p == NULL)
    {
        return ERR_OK;
    }

    /* points to packet payload, which starts with an Ethernet header */
    ethhdr = p->payload;

    switch (htons(ethhdr->type))
    {
    /* IP or ARP packet? */
    case ETHTYPE_IP:
    case ETHTYPE_ARP:
#if PPPOE_SUPPORT
    /* PPPoE packet? */
    case ETHTYPE_PPPOEDISC:
    case ETHTYPE_PPPOE:
#endif /* PPPOE_SUPPORT */

        /* full packet send to tcpip_thread to process */
        if (netif->input(p, netif) != ERR_OK)
        {
            pbuf_free(p);
        }

        break;

    default:
        pbuf_free(p);
        break;
    }

    return ERR_OK;
}


/**
 * Should be called at the beginning of the program to set up the
 * network interface. It calls the function low_level_init() to do the
 * actual setup of the hardware.
 *
 * This function should be passed as a parameter to netif_add().
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return ERR_OK if the loopif is initialized
 *         ERR_MEM if private data couldn't be allocated
 *         any other err_t on error
 */
err_t ifx_netif_init(netif_t *netif)
{
    IfxGeth_Eth *ethernetif;

    LWIP_ASSERT("netif != NULL", (netif != NULL));

    ethernetif = IfxGeth_get();

    if (ethernetif == NULL)
    {
        return ERR_MEM;
    }

#if LWIP_NETIF_HOSTNAME
    /* Initialize interface hostname */
    netif->hostname = "lwip";
#endif /* LWIP_NETIF_HOSTNAME */

    /*
     * Initialize the snmp variables and counters inside the struct netif.
     * The last argument should be replaced with your link speed, in units
     * of bits per second.
     */
    netif->state      = ethernetif;
    netif->name[0]    = IFNAME0;
    netif->name[1]    = IFNAME1;
    netif->output     = etharp_output;
    netif->linkoutput = low_level_output;

    low_level_init(netif);

    return ERR_OK;
}

void ifx_netif_update_link(netif_t *netif)
{
    if (dp83825i_update_link(&g_phy) != 0)
    {
        ifxNetifApplyLinkState(netif);
    }
}
