/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "Ifx_Cfg.h"
#include "IfxCpu.h"
#include "IfxStm.h"
#include "IfxWtu.h"

#include <stdio.h>

#include "Configuration.h"
#include "DreCanEthBridge.h"
#include "EthernetMacEeprom.h"
#include "serialio.h"

#define UART_BAUDRATE 115200

volatile uint32 g_TickCount_1ms;

static const uint8 g_fallbackMacAddress[ETHERNET_MAC_EEPROM_LENGTH] = {0x02U, 0x00U, 0x5EU, 0x4DU, 0x70U, 0x01U};

static void printStartupBanner(void)
{
    printf("\r\n");
    printf("========================================\r\n");
    printf(" TC4D7 DRE CAN/Ethernet bridge\r\n");
    printf(" UART0 TX=P14.0 RX=P14.1, 115200-8-N-1\r\n");
    printf(" CAN01      : 500K@80%% arbitration, 2M@80%% data\r\n");
    printf(" PHY        : DP83825I (RMII, GETH0 Port0)\r\n");
    printf(" DRE        : IEEE1722 ACF <-> CAN bridge\r\n");
    printf("========================================\r\n");
}

static void initSystemTick(void)
{
    IfxStm_CompareConfig compareConfig;

    IfxStm_initCompareConfig(&compareConfig);
    compareConfig.triggerPriority = ISR_PRIORITY_OS_TICK;
    compareConfig.comparatorInterrupt = IfxStm_ComparatorInterrupt_ir0;
    compareConfig.ticks = IFX_CFG_STM_TICKS_PER_MS;
    compareConfig.typeOfService = IfxSrc_Tos_cpu0;

    IfxStm_initCompare(&MODULE_CPU0, &compareConfig);
}

void core0_main(void)
{
    uint8 macAddress[ETHERNET_MAC_EEPROM_LENGTH];
    boolean macReadOk;

    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());

    SERIALIO_Init(UART_BAUDRATE);
    initSystemTick();
    printStartupBanner();

    macReadOk = EthernetMacEeprom_read(macAddress);

    if (macReadOk == FALSE)
    {
        uint32 index;

        for (index = 0U; index < ETHERNET_MAC_EEPROM_LENGTH; ++index)
        {
            macAddress[index] = g_fallbackMacAddress[index];
        }

        printf("EEPROM MAC read failed, using fallback MAC address.\r\n");
    }
    else
    {
        printf("EEPROM MAC read succeeded.\r\n");
    }

    printf("MAC address: %02X:%02X:%02X:%02X:%02X:%02X\r\n",
           macAddress[0], macAddress[1], macAddress[2],
           macAddress[3], macAddress[4], macAddress[5]);

    DreCanEthBridge_init(macAddress);

    while (1)
    {
        DreCanEthBridge_poll();
    }
}

IFX_INTERRUPT(updateLwipStackIsr, 0, ISR_PRIORITY_OS_TICK);

void updateLwipStackIsr(void)
{
    IfxStm_clearCompareFlag(&MODULE_CPU0, IfxStm_Comparator_0);
    IfxStm_increaseCompare(&MODULE_CPU0, IfxStm_Comparator_0, IFX_CFG_STM_TICKS_PER_MS);

    g_TickCount_1ms += IFX_CFG_STM_TIMER_PERIOD_MS;
}
