/**********************************************************************************************************************
 * \file UART_Logging.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "UART_Logging.h"
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include <stdint.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SERIAL_BAUDRATE         921600                                      /* Baud rate in bit/s  — 921600 high-speed */
#define SERIAL_TX_FIFO_LEVEL    8
#define SERIAL_RX_FIFO_LEVEL    1   /* Must be 1 for shell: trigger RX ISR per byte, else short commands (<8B) stay in HW FIFO */

#define SERIAL_PIN_RX           IfxAsclin4_RXA_P00_12_IN                     /* RX pin of the board                  */
#define SERIAL_PIN_TX           IfxAsclin4_TX_P00_9_OUT                     /* TX pin of the board                  */

/* RX higher than TX; both higher than STM tick to avoid overrun at 921600 */
#define INTPRIO_ASCLIN4_TX      31                                          /* Priority of the TX ISR                 */
#define INTPRIO_ASCLIN4_RX      32                                          /* Priority of the RX ISR (higher than TX) */

#define ASC_TX_BUFFER_SIZE      1024                                        /* TX SW FIFO — enlarged for burst printf */
#define ASC_RX_BUFFER_SIZE      1024                                        /* RX SW FIFO — enlarged for 921600 */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxAsclin_Asc g_asc;                                                        /* Declaration of the ASC handle        */
uint8 g_ascTxBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];             /* Declaration of the FIFO parameters   */
uint8 g_ascRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];

/* Forward declaration from shell_port.c */
extern void Shell_RxPush(uint8_t ch);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(asclin4TxISR, 0, INTPRIO_ASCLIN4_TX);                     /* Adding the Interrupt Service Routine     */
IFX_INTERRUPT(asclin4RxISR, 0, INTPRIO_ASCLIN4_RX);

void asclin4TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&g_asc);
}

void asclin4RxISR(void)
{
    IfxAsclin_Asc_isrReceive(&g_asc);
    /* Bulk drain SW FIFO into shell ring — avoids per-byte driver lock overhead */
    sint32 avail = IfxAsclin_Asc_getReadCount(&g_asc);
    if (avail > 0) {
        uint8 bulk[64];
        while (avail > 0) {
            Ifx_SizeT chunk = (avail > (sint32)sizeof(bulk)) ? sizeof(bulk) : (Ifx_SizeT)avail;
            Ifx_SizeT cnt = chunk;
            if (IfxAsclin_Asc_read(&g_asc, bulk, &cnt, TIME_NULL) == IfxAsclin_Status_noError && cnt > 0) {
                for (Ifx_SizeT i = 0; i < cnt; ++i) {
                    Shell_RxPush(bulk[i]);
                }
                avail -= (sint32)cnt;
                if (cnt != chunk) break;
            } else {
                break;
            }
        }
    }
}

/* Optimized poll: only used as fallback if an RX interrupt was missed.
 * We disable interrupts around isrReceive to avoid re-entrancy with asclin4RxISR,
 * then bulk-drain to shell ring.
 */
void UART_Poll(void)
{
    /* Fast path: if SW FIFO already has data, just drain it */
    sint32 swAvail = IfxAsclin_Asc_getReadCount(&g_asc);
    if (swAvail > 0) {
        uint8 bulk[64];
        while (swAvail > 0) {
            Ifx_SizeT chunk = (swAvail > (sint32)sizeof(bulk)) ? sizeof(bulk) : (Ifx_SizeT)swAvail;
            Ifx_SizeT cnt = chunk;
            if (IfxAsclin_Asc_read(&g_asc, bulk, &cnt, TIME_NULL) == IfxAsclin_Status_noError && cnt > 0) {
                for (Ifx_SizeT i = 0; i < cnt; ++i) Shell_RxPush(bulk[i]);
                swAvail -= (sint32)cnt;
                if (cnt != chunk) break;
            } else break;
            swAvail = IfxAsclin_Asc_getReadCount(&g_asc);
            /* only one bulk iteration per poll to keep main loop responsive */
            break;
        }
        return;
    }
    /* HW FIFO has data but SW FIFO empty => interrupt missed, recover */
    if (MODULE_ASCLIN4.FLAGS.B.RFL) {
        boolean ie = IfxCpu_disableInterrupts();
        IfxAsclin_Asc_isrReceive(&g_asc);
        IfxCpu_restoreInterrupts(ie);
        swAvail = IfxAsclin_Asc_getReadCount(&g_asc);
        if (swAvail > 0) {
            uint8 bulk[64];
            Ifx_SizeT cnt = (swAvail > (sint32)sizeof(bulk)) ? sizeof(bulk) : (Ifx_SizeT)swAvail;
            Ifx_SizeT c = cnt;
            if (IfxAsclin_Asc_read(&g_asc, bulk, &c, TIME_NULL) == IfxAsclin_Status_noError && c > 0) {
                for (Ifx_SizeT i = 0; i < c; ++i) Shell_RxPush(bulk[i]);
            }
        }
    }
}

void initUART(void)
{
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN4);
    ascConfig.baudrate.baudrate = SERIAL_BAUDRATE;
    /* High-speed tuning for 921600: oversampling 16, median filter 3, sample point 12 */
    ascConfig.baudrate.oversampling = IfxAsclin_OversamplingFactor_16;
    ascConfig.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three;
    ascConfig.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_12;
    ascConfig.baudrate.prescaler = 1;
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN4_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN4_RX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());
    ascConfig.interrupt.erPriority = 0; /* no error ISR needed */
    ascConfig.txBuffer = &g_ascTxBuffer;
    ascConfig.txBufferSize = ASC_TX_BUFFER_SIZE;
    ascConfig.rxBuffer = &g_ascRxBuffer;
    ascConfig.rxBufferSize = ASC_RX_BUFFER_SIZE;
    /* FIFO interrupt levels: fire earlier (lower) for TX, moderate for RX to reduce ISR count */
    ascConfig.fifo.txFifoInterruptLevel = SERIAL_TX_FIFO_LEVEL;
    ascConfig.fifo.rxFifoInterruptLevel = SERIAL_RX_FIFO_LEVEL;
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,         IfxPort_InputMode_pullUp,
        &SERIAL_PIN_RX,   IfxPort_InputMode_pullUp,
        NULL_PTR,         IfxPort_OutputMode_pushPull,
        &SERIAL_PIN_TX,   IfxPort_OutputMode_pushPull,
        IfxPort_PadDriver_cmosAutomotiveSpeed4
    };
    ascConfig.pins = &pins;
    IfxAsclin_Asc_initModule(&g_asc, &ascConfig);
    /* Ensure FIFOs enabled */
    MODULE_ASCLIN4.RXFIFOCON.B.ENI = 1;
    MODULE_ASCLIN4.TXFIFOCON.B.ENO = 1;
}

void sendUARTMessage(char * msg, Ifx_SizeT count)
{
    IfxAsclin_Asc_write(&g_asc, msg, &count, TIME_INFINITE);            /* Transfer of data                         */
}

/* Provide _write for printf retarget */
int _write(int file, char *ptr, int len)
{
    (void)file;
    if (ptr == NULL || len <= 0) return 0;
    Ifx_SizeT cnt = (Ifx_SizeT)len;
    IfxAsclin_Asc_write(&g_asc, (uint8_t*)ptr, &cnt, TIME_INFINITE);
    return (int)cnt;
}

int _read(int file, char *ptr, int len)
{
    (void)file;
    int i = 0;
    for (i = 0; i < len; ++i) {
        uint8 ch;
        Ifx_SizeT cnt = 1;
        /* Non-blocking try: if FIFO has data, read one char */
        if (IfxAsclin_Asc_getReadCount(&g_asc) == 0) break;
        if (IfxAsclin_Asc_read(&g_asc, &ch, &cnt, TIME_NULL) != IfxAsclin_Status_noError || cnt == 0) break;
        ptr[i] = (char)ch;
    }
    return i;
}
