/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxStm.h"
#include "Ifx_reg.h"
#include "IfxScuRcu.h"
#include "IfxGeth_Eth.h"
#include "Ifx_Console.h"
#include "Configuration.h"
#include "ConfigurationIsr.h"
#include "Ifx_Lwip.h"
#include "lwip/apps/lwiperf.h"
#include "lwip/udp.h"
#include "Bsp.h"
#include "IfxGeth_reg.h"
#include <stdio.h>
#include <string.h>

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxCpu_syncEvent cpuSyncEvent = 0;

#if LWIP_TCP
static void
lwiperf_report(void *arg, enum lwiperf_report_type report_type,
  const ip_addr_t* local_addr, u16_t local_port, const ip_addr_t* remote_addr, u16_t remote_port,
  u64_t bytes_transferred, u32_t ms_duration, u32_t bandwidth_kbitpsec)
{
  LWIP_UNUSED_ARG(arg);
  LWIP_UNUSED_ARG(local_addr);
  LWIP_UNUSED_ARG(local_port);

  Ifx_Lwip_printf("IPERF report: type=%d, remote: %s:%d, total bytes: %llu, duration in ms: %"U32_F", kbits/s: %"U32_F"",
    (int)report_type, ipaddr_ntoa(remote_addr), (int)remote_port, (unsigned long long)bytes_transferred, ms_duration, bandwidth_kbitpsec);
}
#endif /* LWIP_TCP */

/*********************************************************************************************************************/
/*------------------------------------------UDP diagnostic service (port 5002)---------------------------------------*/
/*********************************************************************************************************************/
extern volatile uint32 g_diag_rx_ok, g_diag_rx_err, g_diag_rx_nobuf, g_diag_tx_pkts;
extern volatile uint32 g_prof_copy_ticks, g_prof_copy_cnt;
extern volatile uint32 g_prof_input_ticks, g_prof_input_cnt;
extern volatile uint32 g_prof_tx_ticks, g_prof_tx_cnt;
extern volatile uint32 g_prof_poll_gap_max, g_prof_poll_gap_1ms, g_diag_rbu;
extern volatile uint32 g_prof_busy_ticks, g_prof_idle_polls, g_prof_alloc_ticks;
extern uint32 isrRxCount, isrTxCount;
static volatile unsigned long g_diag_rdval;

static void diag_udp_recv(void *arg, struct udp_pcb *pcb, struct pbuf *p, const ip_addr_t *addr, u16_t port)
{
    static char msg[512];   /* static: a 512B frame would overflow the task stack */
    static char cmd[64];
    int  n;
    LWIP_UNUSED_ARG(arg);
    if (p != NULL)
    {
        /* Runtime tuning commands (avoids a reflash per experiment):
         *   "fc <rfa> <rfd> <pauseTime>"  - 802.3x flow control thresholds
         *   "z"                           - zero the software profiling counters */
        u16_t l = (p->tot_len < (u16_t)(sizeof(cmd) - 1)) ? p->tot_len : (u16_t)(sizeof(cmd) - 1);
        pbuf_copy_partial(p, cmd, l, 0);
        cmd[l] = '\0';
        pbuf_free(p);

        if (cmd[0] == 'f' && cmd[1] == 'c')
        {
            unsigned rfa = 1, rfd = 4, pt = 0x1000;
            if (sscanf(&cmd[2], "%u %u %u", &rfa, &rfd, &pt) == 3)
            {
                if (pt == 0u)
                {   /* pt == 0 disables 802.3x flow control entirely */
                    GETH_MTL_RXQ0_OPERATION_MODE.B.EHFC = 0;
                    GETH_MAC_Q0_TX_FLOW_CTRL.U = 0;
                }
                else
                {
                    GETH_MTL_RXQ0_OPERATION_MODE.B.RFA  = rfa & 0xF;
                    GETH_MTL_RXQ0_OPERATION_MODE.B.RFD  = rfd & 0xF;
                    GETH_MTL_RXQ0_OPERATION_MODE.B.EHFC = 1;
                    GETH_MAC_Q0_TX_FLOW_CTRL.U = ((uint32)(pt & 0xFFFF) << 16) | (4u << 4) | (1u << 1);
                }
            }
        }
        else if (cmd[0] == 'w' && cmd[1] == 'r')
        {
            /* "wr <offset_hex> <value_hex>" - write a GETH register
             * (offset from 0xF001D000, restricted to the GETH 8KB space). */
            unsigned long off = 0, val = 0;
            if (sscanf(&cmd[2], "%lx %lx", &off, &val) == 2 && off < 0x2000ul)
            {
                *(volatile unsigned long *)(0xF001D000ul + (off & ~3ul)) = val;
            }
        }
        else if (cmd[0] == 'r' && cmd[1] == 'd')
        {
            /* "rd <offset_hex>" - read a GETH register into g_diag_rdval */
            unsigned long off = 0;
            if (sscanf(&cmd[2], "%lx", &off) == 1 && off < 0x2000ul)
            {
                g_diag_rdval = *(volatile unsigned long *)(0xF001D000ul + (off & ~3ul));
            }
        }
        else if (cmd[0] == 'z')
        {
            g_prof_copy_ticks = 0; g_prof_copy_cnt = 0;
            g_prof_input_ticks = 0; g_prof_input_cnt = 0;
            g_prof_tx_ticks = 0; g_prof_tx_cnt = 0;
            g_prof_busy_ticks = 0; g_prof_idle_polls = 0;
            g_prof_alloc_ticks = 0; g_diag_rx_ok = 0; g_diag_tx_pkts = 0;
        }
    }
    n = snprintf(msg, sizeof(msg),
        "rdval=0x%08lx tick=%lu isrRx=%lu isrTx=%lu rx_ok=%lu rx_err=%lu rx_nobuf=%lu tx=%lu "
        "hw_rxgb=%lu hw_crc=%lu hw_fifo_ovf=%lu hw_missed=%lu dma_ch0_status=0x%08lx "
        "copy_t=%lu copy_n=%lu input_t=%lu input_n=%lu tx_t=%lu tx_n=%lu "
        "gap_max=%lu gap1ms=%lu phy_cs=0x%08lx rbu=%lu dma_miss=%lu "
        "busy_t=%lu idle_p=%lu alloc_t=%lu txpause=%lu fcpu=%lu fstm=%lu fsri=%lu fgeth=%lu "
        "sysbus=0x%08lx rxctl=0x%08lx txctl=0x%08lx rxqop=0x%08lx rxqdbg=0x%08lx txqop=0x%08lx\n",
        g_diag_rdval,
        (unsigned long)g_TickCount_1ms,
        (unsigned long)isrRxCount, (unsigned long)isrTxCount,
        (unsigned long)g_diag_rx_ok, (unsigned long)g_diag_rx_err,
        (unsigned long)g_diag_rx_nobuf, (unsigned long)g_diag_tx_pkts,
        (unsigned long)GETH_RX_PACKETS_COUNT_GOOD_BAD.U,
        (unsigned long)GETH_RX_CRC_ERROR_PACKETS.U,
        (unsigned long)GETH_RX_FIFO_OVERFLOW_PACKETS.U,
        (unsigned long)GETH_MTL_RXQ0_MISSED_PACKET_OVERFLOW_CNT.U,
        (unsigned long)GETH_DMA_CH0_STATUS.U,
        (unsigned long)g_prof_copy_ticks, (unsigned long)g_prof_copy_cnt,
        (unsigned long)g_prof_input_ticks, (unsigned long)g_prof_input_cnt,
        (unsigned long)g_prof_tx_ticks, (unsigned long)g_prof_tx_cnt,
        (unsigned long)g_prof_poll_gap_max, (unsigned long)g_prof_poll_gap_1ms,
        (unsigned long)GETH_MAC_PHYIF_CONTROL_STATUS.U,
        (unsigned long)g_diag_rbu,
        (unsigned long)GETH_DMA_CH0_MISS_FRAME_CNT.U,
        (unsigned long)g_prof_busy_ticks, (unsigned long)g_prof_idle_polls,
        (unsigned long)g_prof_alloc_ticks,
        (unsigned long)GETH_TX_PAUSE_PACKETS.U,
        (unsigned long)IfxScuCcu_getCpuFrequency(IfxCpu_getCoreIndex()),
        (unsigned long)IfxStm_getFrequency(&MODULE_STM0),
        (unsigned long)IfxScuCcu_getSriFrequency(),
        (unsigned long)(IfxScuCcu_getSriFrequency() / (MODULE_SCU.CCUCON5.B.GETHDIV ? MODULE_SCU.CCUCON5.B.GETHDIV : 1u)),
        (unsigned long)GETH_DMA_SYSBUS_MODE.U,
        (unsigned long)GETH_DMA_CH0_RX_CONTROL.U,
        (unsigned long)GETH_DMA_CH0_TX_CONTROL.U,
        (unsigned long)GETH_MTL_RXQ0_OPERATION_MODE.U,
        (unsigned long)GETH_MTL_RXQ0_DEBUG.U,
        (unsigned long)GETH_MTL_TXQ0_OPERATION_MODE.U);
    if (n > 0)
    {
        struct pbuf *r = pbuf_alloc(PBUF_TRANSPORT, (u16_t)n, PBUF_RAM);
        if (r != NULL)
        {
            memcpy(r->payload, msg, (size_t)n);
            udp_sendto(pcb, r, addr, port);
            pbuf_free(r);
        }
    }
}

/* Bit-bucket sink on port 5003: lets an external UDP blaster measure the raw
 * RX capability (DMA + copy + IP/UDP demux) without any TCP processing. */
static void sink_udp_recv(void *arg, struct udp_pcb *pcb, struct pbuf *p, const ip_addr_t *addr, u16_t port)
{
    LWIP_UNUSED_ARG(arg); LWIP_UNUSED_ARG(pcb);
    LWIP_UNUSED_ARG(addr); LWIP_UNUSED_ARG(port);
    if (p != NULL)
    {
        pbuf_free(p);
    }
}

static void diag_udp_init(void)
{
    struct udp_pcb *pcb = udp_new();
    if (pcb != NULL)
    {
        udp_bind(pcb, IP_ANY_TYPE, 5002);
        udp_recv(pcb, diag_udp_recv, NULL);
    }

    pcb = udp_new();
    if (pcb != NULL)
    {
        udp_bind(pcb, IP_ANY_TYPE, 5003);
        udp_recv(pcb, sink_udp_recv, NULL);
    }
}

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void core0_main (void)
{
    /* Enable the global interrupts of this CPU */
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event: wait until all CPUs are in CpuX_Main to avoid variables' initialization problems */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    // eth PHY RESET
    IfxPort_setPinModeOutput(&MODULE_P11,15, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinLow(&MODULE_P11,15);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 90));
    IfxPort_setPinHigh(&MODULE_P11,15);
    waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 10));

    IfxStm_CompareConfig stmCompareConfig;                                  /* STM Configuration declaration                */
    IfxStm_initCompareConfig(&stmCompareConfig);                            /* Initialize a default configuration for STM   */
    stmCompareConfig.triggerPriority     = ISR_PRIORITY_OS_TICK;            /* Priority of the interrupt generated by STM   */
    stmCompareConfig.comparatorInterrupt = IfxStm_ComparatorInterrupt_ir0;  /* Select the request source 0                  */
    stmCompareConfig.ticks               = IFX_CFG_STM_TICKS_PER_MS * 10;   /* First interrupt shall occur after 10 ms      */
    stmCompareConfig.typeOfService       = IfxSrc_Tos_cpu0;                 /* CPU0 serves the interrupts                   */
    IfxStm_initCompare(&MODULE_STM0, &stmCompareConfig);                    /* Initialize the Compare functionality         */

    IfxGeth_enableModule(&MODULE_GETH);                     /* Enable Gigabit Ethernet Media Access Controller (GETH) module*/

    /* Define a MAC Address */
    eth_addr_t ethAddr;
    ethAddr.addr[0] = 0xDE;
    ethAddr.addr[1] = 0xAD;
    ethAddr.addr[2] = 0xBE;
    ethAddr.addr[3] = 0xEF;
    ethAddr.addr[4] = 0xFE;
    ethAddr.addr[5] = 0xED;

    ip_addr_t ipAddr    = IPADDR4_INIT_BYTES(192, 168,   0, 100); /* IP address  */
    ip_addr_t netMask   = IPADDR4_INIT_BYTES(255, 255, 255,   0); /* Netmask     */
    ip_addr_t gateway   = IPADDR4_INIT_BYTES(192, 168,   0,   1); /* Gateway     */

    Ifx_Lwip_init_with_ip(ethAddr, ipAddr, netMask, gateway);     /* Initialize LwIP with static IP */

#if LWIP_TCP
    lwiperf_start_tcp_server_default(lwiperf_report, NULL);
#endif
    diag_udp_init();

    while (1)
    {
        Ifx_Lwip_pollTimerFlags();
        Ifx_Lwip_pollReceiveFlags();
    }
}

/* This interrupt is raised by the STM0 */
IFX_INTERRUPT (updateLwIPStackISR, 0, ISR_PRIORITY_OS_TICK);

/* ISR to update LwIP stack */
void updateLwIPStackISR(void)
{
    /* Configure STM to generate an interrupt in 1 ms */
    IfxStm_increaseCompare(&MODULE_STM0, IfxStm_Comparator_0, IFX_CFG_STM_TICKS_PER_MS);

    g_TickCount_1ms++;                                      /* Increase LwIP system time                                    */

    Ifx_Lwip_onTimerTick();                                 /* Every 1 ms LwIP timers are increased for all the enabled
                                                             * protocols (ARP, TCP, DHCP, LINK)                             */
}
