/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "Ifx_Cfg.h"
#include "IfxCpu.h"
#include "IfxWtu.h"
#include "Bsp.h"
#include <stdio.h>

#include "serialio.h"
#include "AdcMonitor.h"

#define UART_BAUDRATE        115200
#define REPORT_PERIOD_MS     500U

static void printStartupBanner(void)
{
    printf("\r\n");
    printf("************************************\r\n");
    printf("*        TC4D7 ADC Monitor         *\r\n");
    printf("************************************\r\n");
    printf("UART0 TX=P14.0 RX=P14.1, 115200-8-N-1\r\n");
    printf("AN0 uses TMADC0 Channel 0.\r\n");
    printf("Internal temperature uses PMS DTS.\r\n");
}


void core0_main(void)
{
    AdcMonitor_Reading reading;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());

    SERIALIO_Init(UART_BAUDRATE);
    printStartupBanner();
    AdcMonitor_init();

    printf("Sampling every %u ms. Rotate the potentiometer connected to AN0.\r\n", REPORT_PERIOD_MS);
    
    while (1)
    {
        if (AdcMonitor_sample(&reading) != FALSE)
        {
            if (reading.temperatureValid != FALSE)
            {
                printf("AN0 raw=%4u  ratio=%6.2f%%  voltage=%.3f V  DTS raw=%4u  temp=%.2f C\r\n",
                    reading.potiRaw,
                    reading.potiRatio * 100.0f,
                    reading.potiVoltage,
                    reading.temperatureRaw,
                    reading.temperatureCelsius);
            }
            else
            {
                printf("AN0 raw=%4u  ratio=%6.2f%%  voltage=%.3f V  DTS warming up (raw=%4u)\r\n",
                    reading.potiRaw,
                    reading.potiRatio * 100.0f,
                    reading.potiVoltage,
                    reading.temperatureRaw);
            }
        }

        waitTime(IfxStm_getTicksFromMilliseconds(REPORT_PERIOD_MS));
    }
}
