/**********************************************************************************************************************
 * \file lwiopts.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef __LWIPOPTS_H__
#define __LWIPOPTS_H__

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define NO_SYS                  1                   /* Use LwIP without Operating System (no threads, no semaphores, etc.)  */
#define LWIP_NETIF_HOSTNAME     1                   /* Enable hostname option in DHCP                                       */

#define BOARDNAME               "AURIX_TC387"     /* Board name, also used as hostname                                    */

#define MEM_ALIGNMENT           4                   /* Set memory alignment to 4 byte (32-bit machine)                      */
#define MEM_SIZE                (76 * 1024)         /* Heap: PBUF_POOL(32*~1.5KB) + TCP segs + margin, fits DSPR0            */
#define LWIP_RAM_HEAP_POINTER   lwip_lmuram_heap   /* Heap in LMURAM for multi-core access                                 */
#define LWIP_DHCP               0                   /* Enable DHCP protocol                                                 */
#define LWIP_NETCONN            0                   /* Disable Netconn API                                                  */
#define LWIP_SOCKET             0                   /* Disable the Socket API                                               */

// iperf tcp optimizations
#define TCP_MSS                 1460
#define TCP_WND                 (44 * TCP_MSS)      /* RX window: 64240 (max without RFC1323 scaling) */
#define TCP_SND_BUF             (44 * TCP_MSS)      /* TX buffer: 64240 */
#define MEMP_NUM_TCP_SEG        44                  /* in-flight segments for one stream (window/MSS) */
#define MEMP_NUM_PBUF           64                  /* PBUF headers available */
#define PBUF_POOL_SIZE          32                  /* PBUF_POOL: copy-based RX needs one pbuf per frame */
#define TCP_QUEUE_OOSEQ         1                   /* queue OOO segs: one lost pkt must NOT discard the rest of the window */
#define TCP_OOSEQ_MAX_PBUFS     16                  /* cap OOO queue so PBUF_POOL is not exhausted */
#define LWIP_DISABLE_TCP_SANITY_CHECKS 1
#define LWIP_STATS              0                   /* No statistic counters in hot path */
#define LWIP_NOASSERT           1                   /* tcp_input runs dozens of asserts per packet - too hot for 1Gbps */

/* GETH COE: HW verifies/inserts IP/TCP/UDP/ICMP checksums (MAC_CONFIGURATION.IPC + TDES3.CIC) */
#define CHECKSUM_GEN_IP         0
#define CHECKSUM_GEN_UDP        0
#define CHECKSUM_GEN_TCP        0
#define CHECKSUM_GEN_ICMP       0
#define CHECKSUM_CHECK_IP       0
#define CHECKSUM_CHECK_UDP      0
#define CHECKSUM_CHECK_TCP      0
#define CHECKSUM_CHECK_ICMP     0

#define ETH_PAD_SIZE            0                   /* No padding needed                                                    */

/* IMPORTANT: LwIP debug printing goes through the UART. At 115200 baud that is
 * only ~275 lines/s, so a per-packet LWIP_DEBUGF() in the RX path throttles
 * throughput to a few Mbit/s. The port (arch/cc.h) REQUIRES LWIP_DEBUG to be
 * defined (else #error), so we keep __LWIP_DEBUG__ defined but set every
 * specific debug level (esp. NETIF_DEBUG) to LWIP_DBG_OFF below, which makes
 * LWIP_DEBUGF() a no-op (zero overhead, no UART traffic). */
#define __LWIP_DEBUG__                              /* Required by arch/cc.h (do NOT remove) */

#define LWIP_NETIF_EXT_STATUS_CALLBACK  1           /* Enable an extended callback function for netif                       */

#ifdef __LWIP_DEBUG__
#define LWIP_DEBUG                                  /* Enable LwIP debugging                                                */
#endif

#ifndef IFX_LWIP_DEBUG
#define IFX_LWIP_DEBUG          LWIP_DBG_OFF        /* IFX LwIP debug level set to OFF                                      */
#endif
#define DHCP_DEBUG              LWIP_DBG_OFF        /* Enable DHCP Debug                                                    */
#define NETIF_DEBUG             LWIP_DBG_OFF        /* DISABLED: per-packet UART print kills throughput                    */
#define LWIP_DBG_TYPES_ON       LWIP_DBG_STATE      /* Enable only module state debug messages                              */

#ifdef __GNUC__
    /* to avoid compiler error for double declaration we inform GNUC that ssize_t is declared by lwip */
    #define _SSIZE_T_DECLARED
#endif

#endif /* __LWIPOPTS_H__ */

