/**********************************************************************************************************************
 * \file Ifx_Cfg.h
 * \brief Project configuration file.
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef IFX_CFG_H
#define IFX_CFG_H 1

/*********************************************************************************************************************/
/*---------------------------------------- Configuration for IfxClock_cfg.h -----------------------------------------*/
/*********************************************************************************************************************/
/* External oscillator frequency in Hz */
#define IFX_CFG_CLOCK_XTAL_FREQUENCY    (25000000)  /* Allowed values are: 40000000, 25000000, 20000000, 16000000 */
/* System PLL frequency in Hz */
#define IFX_CFG_CLOCK_SYSPLL_FREQUENCY  (500000000) /* Allowed values are: 300000000, 200000000, 160000000, 133000000
                                                     * or 80000000 */
/* PPU PLL frequency in Hz */
#define IFX_CFG_CLOCK_PPUPLL_FREQUENCY  (450000000) /* Allowed values are: 
                                                     *  - 450000000 (If IFX_CFG_CLOCK_SYSPLL_FREQUENCY = 500MHz)
                                                     *  - 400000000 (If IFX_CFG_CLOCK_SYSPLL_FREQUENCY = 400MHz) */
/* Peripheral PLL1 frequency in Hz */
#define IFX_CFG_CLOCK_PERPLL1_FREQUENCY (160000000) /* Allowed values are: 320000000, 160000000 */
/* Peripheral PLL2 frequency in Hz */
#define IFX_CFG_CLOCK_PERPLL2_FREQUENCY (200000000) /* Allowed value: 200000000 */
/* Peripheral PLL3 frequency in Hz */
#define IFX_CFG_CLOCK_PERPLL3_FREQUENCY (200000000) /* Allowed value: 200000000 */

/*********************************************************************************************************************/
/*-----------------------------------Configuration for Software managed interrupt------------------------------------*/
/*********************************************************************************************************************/
/* #define IFX_PROT_ENABLED 1 */
/* #define IFX_USE_SW_MANAGED_INT */ /* Decomment this line if the project needs to use Software managed interrupts */

/* STM resolution in Hz */
#define IFX_STM_RESOULTION              IFX_CFG_CLOCK_SYSPLL_FREQUENCY

#define IFX_CFG_INTERRUPT_INTERVAL      (0.003)

#define IFX_CFG_CPU0_PRIO               10
#define IFX_CFG_CPU1_PRIO               10
#define IFX_CFG_CPU2_PRIO               10
#define IFX_CFG_CPU3_PRIO               10
#define IFX_CFG_CPU4_PRIO               10
#define IFX_CFG_CPU5_PRIO               10

/*********************************************************************************************************************/
/*---------------------------------Configuration for Trap Hook Functions' Extensions---------------------------------*/
/*********************************************************************************************************************/
#define IFX_CFG_EXTEND_TRAP_HOOKS

/*********************************************************************************************************************/
/*---------------------------------SSW Diagnostic: DSPR-local step markers-------------------------------------------*/
/*********************************************************************************************************************/
#define DIAG_DSPR_SSW_STEP   (*(volatile unsigned int *)0xD0000000)
#define DIAG_DSPR_TRAP_CLASS (*(volatile unsigned int *)0xD0000004)
#define DIAG_DSPR_TRAP_ID    (*(volatile unsigned int *)0xD0000008)
#define DIAG_DSPR_TRAP_ADDR  (*(volatile unsigned int *)0xD000000C)
#define DIAG_DSPR_TRAP_COUNT (*(volatile unsigned int *)0xD0000010)
#define DIAG_DSPR_TRAP_DEADD (*(volatile unsigned int *)0xD0000014)
#define DIAG_DSPR_TRAP_DATR  (*(volatile unsigned int *)0xD0000018)
#define DIAG_DSPR_WORKER_RES     (*(volatile unsigned int *)0xD0000020)
#define DIAG_DSPR_WORKER_LIST    (*(volatile unsigned int *)0xD0000024)
#define DIAG_DSPR_WORKER_MB0     (*(volatile unsigned int *)0xD0000028)
#define DIAG_DSPR_WORKER_MB1     (*(volatile unsigned int *)0xD000002C)
#define DIAG_DSPR_WORKER_LNEXT   (*(volatile unsigned int *)0xD0000030)
#define DIAG_DSPR_WORKER_LINFO   (*(volatile unsigned int *)0xD0000034)
#define DIAG_DSPR_WORKER_NINFO   (*(volatile unsigned int *)0xD0000038)
#define DIAG_DSPR_WORKER_SEEN    (*(volatile unsigned int *)0xD000003C)
#define DIAG_DSPR_WORKER_DONE    (*(volatile unsigned int *)0xD0000040)
#define DIAG_DSPR_WORKER_CRCLIST (*(volatile unsigned int *)0xD0000044)
#define DIAG_DSPR_WORKER_CRCMAT  (*(volatile unsigned int *)0xD0000048)
#define DIAG_DSPR_WORKER_CRCSTATE (*(volatile unsigned int *)0xD000004C)
#define DIAG_DSPR_WORKER_CRCFINAL (*(volatile unsigned int *)0xD0000050)
#define SSW_DIAG_STEP(n) do { DIAG_DSPR_SSW_STEP = (unsigned int)(n); } while(0)

/*********************************************************************************************************************/
/*-----------------------------------------------Configuration for Device -------------------------------------------*/
/*********************************************************************************************************************/

#define DEVICE_TC4DX			         1

/* #define IFX_PIN_PACKAGE_BGA436_COM    1 */  /* Configuration for AURIX TC4D9 COM device */
#define IFX_PIN_PACKAGE_BGA292_COM       1     /* Configuration for AURIX TC4D7 COM device */

#endif /* IFX_CFG_H */
