/**********************************************************************************************************************
 * \file Configuration.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


#ifndef CONFIGURATION_H
#define CONFIGURATION_H
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Cfg.h"
#include <_PinMap/IfxGeth_PinMap.h>
#include "ConfigurationIsr.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Pins for RTL8211F RMII connection */
#define ETH_GREFCLK_PIN             IfxGeth_GREFCLK_P11_5_IN
#define ETH_RXCTL_PIN               IfxGeth_RXCTLA_P11_11_IN
#define ETH_RXCLK_PIN               IfxGeth_RXCLKA_P11_12_IN
#define ETH_RXD0_PIN                IfxGeth_RXD0A_P11_10_IN
#define ETH_RXD1_PIN                IfxGeth_RXD1A_P11_9_IN
#define ETH_RXD2_PIN                IfxGeth_RXD2A_P11_8_IN
#define ETH_RXD3_PIN                IfxGeth_RXD3A_P11_7_IN
#define ETH_MDC_PIN                 IfxGeth_MDC_P12_0_OUT
#define ETH_MDIO_PIN                IfxGeth_MDIO_P12_1_INOUT
#define ETH_TXD0_PIN                IfxGeth_TXD0_P11_3_OUT
#define ETH_TXD1_PIN                IfxGeth_TXD1_P11_2_OUT
#define ETH_TXD2_PIN                IfxGeth_TXD2_P11_1_OUT
#define ETH_TXD3_PIN                IfxGeth_TXD3_P11_0_OUT
#define ETH_TXCTL_PIN               IfxGeth_TXCTL_P11_6_OUT
#define ETH_TXCLK_PIN               IfxGeth_TXCLK_P11_4_OUT

#define IFX_CFG_STM_TICKS_PER_MS    (100000)                /* Value of the system timer in ticks per millisecond   */

#define CPU_WHICH_SERVICE_ETHERNET  0                       /* Define the CPU which services the Ethernet           */

#define ISR_PRIORITY_QSPI2_TX       110                         /* QSPI2 TX interrupt priority                      */
#define ISR_PRIORITY_QSPI2_RX       111                         /* QSPI2 RX interrupt priority                      */
#define ISR_PRIORITY_QSPI2_ER       112                         /* QSPI2 ER interrupt priority                      */

/* LAN8651 (10BASE-T1S over TC6 SPI) configuration */
#define LAN8651_RST_PORT             (&MODULE_P15)
#define LAN8651_RST_PIN              (4)
#define LAN8651_INT_PORT             (&MODULE_P15)
#define LAN8651_INT_PIN              (5)

#define LAN8651_SPI_BAUDRATE         (20000000U)

#define LAN8651_FORCE_LINK_UP        (1U)

#define LAN8651_PLCA_ENABLE          (1U)
#define LAN8651_PLCA_NODE_ID         (1U)
#define LAN8651_PLCA_NODE_COUNT      (8U)

#define LAN8651_IP_ADDR0             (192)
#define LAN8651_IP_ADDR1             (168)
#define LAN8651_IP_ADDR2             (1)
#define LAN8651_IP_ADDR3             (100)

#define LAN8651_NETMASK0             (255)
#define LAN8651_NETMASK1             (255)
#define LAN8651_NETMASK2             (255)
#define LAN8651_NETMASK3             (0)

#define LAN8651_GATEWAY0             (192)
#define LAN8651_GATEWAY1             (168)
#define LAN8651_GATEWAY2             (1)
#define LAN8651_GATEWAY3             (1)

#define LAN8651_MAC0                 (0x02U)
#define LAN8651_MAC1                 (0x00U)
#define LAN8651_MAC2                 (0x00U)
#define LAN8651_MAC3                 (0x10U)
#define LAN8651_MAC4                 (0xBAU)
#define LAN8651_MAC5                 (0x5EU)

#endif
