/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "Bsp.h"
#include "IfxPort.h"
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include <stdarg.h>
#include <stdio.h>
#include <inttypes.h>
#include "IfxDts_Dts.h"
#include "Bsp.h"

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;

#define UART_TXBUF_SIZE 256
#define UART_RXBUF_SIZE 256
#define INTPRIO_ASCLIN4_TX 29
#define INTPRIO_ASCLIN4_RX 28

typedef struct
{
    uint8 txBuffer[UART_TXBUF_SIZE + sizeof(Ifx_Fifo) + 8];
    uint8 rxBuffer[UART_RXBUF_SIZE + sizeof(Ifx_Fifo) + 8];
    IfxAsclin_Asc ascHandle;
} App_AsclinAsc;
App_AsclinAsc uart4;

IFX_INTERRUPT(asclin4TxISR, 0, INTPRIO_ASCLIN4_TX);
void asclin4TxISR(void)
{
    IfxAsclin_Asc_isrTransmit(&uart4.ascHandle);
}

IFX_INTERRUPT(asclin4RxISR, 0, INTPRIO_ASCLIN4_RX);
void asclin4RxISR(void)
{
    IfxAsclin_Asc_isrReceive(&uart4.ascHandle);
}

void init_uart4(uint32 baud)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN4);

    /* Set the desired baud rate, 200MHz ASCLINF Freq */
    ascConfig.baudrate.baudrate = (float32)baud; // explicit cast avoids loss when storing in float field
    ascConfig.baudrate.oversampling = IfxAsclin_OversamplingFactor_16;
    ascConfig.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three;
    ascConfig.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_12;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN4_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN4_RX;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.txBuffer = &uart4.txBuffer;
    ascConfig.txBufferSize = UART_TXBUF_SIZE;
    ascConfig.rxBuffer = &uart4.rxBuffer;
    ascConfig.rxBufferSize = UART_RXBUF_SIZE;

    /* Pin configuration */
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,       IfxPort_InputMode_pullUp,     /* CTS pin not used */
        &IfxAsclin4_RXA_P00_12_IN,   IfxPort_InputMode_pullUp,     /* RX pin           */
        NULL_PTR,       IfxPort_OutputMode_pushPull,  /* RTS pin not used */
        &IfxAsclin4_TX_P00_9_OUT,   IfxPort_OutputMode_pushPull,  /* TX pin           */
        IfxPort_PadDriver_cmosAutomotiveSpeed4
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&uart4.ascHandle, &ascConfig); /* Initialize module with above parameters */
}

// print手动实现
void print(const char* fmt, ...)
{
    char buffer[256];
    va_list args;
    va_start(args, fmt);
    int len = vsnprintf(buffer, sizeof(buffer), fmt, args);
    va_end(args);
    if (len > 0)
    {
        Ifx_SizeT wlen = (Ifx_SizeT)len;
        IfxAsclin_Asc_write(&uart4.ascHandle, (uint8*)buffer, &wlen, TIME_INFINITE);
    }
}


#define ISR_PRIORITY_DTS        4
#define MIN_TEMP_LIMIT          -35     /* Lower temperature limit              */
#define MAX_TEMP_LIMIT          150     /* Upper temperature limit              */
volatile uint8 g_isMeasureAvailable = FALSE;     /* Variable to store availability of new measurements */

IFX_INTERRUPT(DTS_ISR, 0, ISR_PRIORITY_DTS);
void DTS_ISR(void)
{
    g_isMeasureAvailable = TRUE; /* Notify the system that a new measurement is ready */
}

/* Function to initialize the Die Temperature Sensor */
void initDieTemperatureSensor(void)
{
    /* Get the default configuration */
    IfxDts_Dts_Config dtsConf;
    IfxDts_Dts_initModuleConfig(&dtsConf);              /* Initialize the structure with default values              */

    dtsConf.lowerTemperatureLimit = MIN_TEMP_LIMIT;     /* Set the lower temperature limit                           */
    dtsConf.upperTemperatureLimit = MAX_TEMP_LIMIT;     /* Set the upper temperature limit                           */
    dtsConf.isrPriority = ISR_PRIORITY_DTS;             /* Set the interrupt priority for new measurement events     */
    dtsConf.isrTypeOfService = IfxSrc_Tos_cpu0;         /* Set the service provider responsible for handling
                                                         * the interrupts                                            */
    IfxDts_Dts_initModule(&dtsConf);                    /* Initialize the DTS with the given configuration           */
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    init_uart4(2000000); /* 设置高波特率，2Mbps，可按需要修改 */
    initDieTemperatureSensor();
    
    while(1)
    {
        if (g_isMeasureAvailable == TRUE)
        {
            // int16 temperatureValue = IfxDts_Dts_getTemperature(); /* Get the latest temperature measurement */
            // print("Die Temperature: %" PRId16 " °C\r\n", temperatureValue);
            float32 temperature = IfxDts_Dts_getTemperatureCelsius();
            print("Die Temperature: %.2f degC\r\n", temperature);
            g_isMeasureAvailable = FALSE; /* Reset the flag */
        }
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 500)); /* Wait for 500 milliseconds */
    }
}
