/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "Ifx_Cfg.h"
#include "IfxCpu.h"
#include "IfxPort.h"
#include "IfxWtu.h"
#include "Bsp.h"


static const IfxPort_Pin g_led1Pin   = {&MODULE_P03, 9};
static const IfxPort_Pin g_led2Pin   = {&MODULE_P03, 10};
static const IfxPort_Pin g_buttonPin = {&MODULE_P03, 11};


static void initGpio(void)
{
    IfxPort_setPinMode(g_led1Pin.port, g_led1Pin.pinIndex, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(g_led2Pin.port, g_led2Pin.pinIndex, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(g_buttonPin.port, g_buttonPin.pinIndex, IfxPort_Mode_inputPullUp);

    IfxPort_setPinHigh(g_led1Pin.port, g_led1Pin.pinIndex);
    IfxPort_setPinHigh(g_led2Pin.port, g_led2Pin.pinIndex);
}


static void updateLedsFromButton(void)
{
    boolean buttonPressed = (IfxPort_getPinState(g_buttonPin.port, g_buttonPin.pinIndex) == 0);

    IfxPort_setPinState(g_led1Pin.port, g_led1Pin.pinIndex, buttonPressed ? IfxPort_State_low : IfxPort_State_high);
    IfxPort_setPinState(g_led2Pin.port, g_led2Pin.pinIndex, buttonPressed ? IfxPort_State_low : IfxPort_State_high);
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());

    initTime();
    initGpio();
    
    while (1)
    {
        updateLedsFromButton();
        waitTime((Ifx_TickTime)(5U * TimeConst_10ms));
    }
}
