/**********************************************************************************************************************
 * \file lwiopts.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef __LWIPOPTS_H__
#define __LWIPOPTS_H__

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define NO_SYS                  1                   /* Use LwIP without Operating System (no threads, no semaphores, etc.)  */
#define LWIP_NETIF_HOSTNAME     1                   /* Enable hostname option in DHCP                                       */

#define BOARDNAME               "AURIX_TC364"       /* Board name, also used as hostname                                    */

#define MEM_ALIGNMENT           4                   /* Set memory alignment to 4 byte (32-bit machine)                      */
/* TC364 DSRAM0 = 192KB. GETH buffers (~41KB) + stacks/CSA (~20KB) are fixed,
 * leaving ~130KB for LwIP. MEM_SIZE is the LwIP heap and also contains the
 * PBUF_POOL (PBUF_POOL_SIZE pbufs of ~1554 bytes each). Keep it modest so .bss
 * ends well below the CPU0 stack/ustack at 0x7002CE00 (~184KB). 48KB heap holds
 * a 32-pbuf pool (~50KB... see note) plus MEMP/TCP buffers; this matches the
 * original example and leaves headroom for the 100M RX burst because the RX path
 * now wakes the DMA and never stalls (see README §8.13). */
#define MEM_SIZE                (40 * 1024)
#define LWIP_DHCP               0                   /* Disable DHCP protocol                                                */
#define LWIP_NETCONN            0                   /* Disable Netconn API                                                  */
#define LWIP_SOCKET             0                   /* Disable the Socket API                                               */
#define SYS_LIGHTWEIGHT_PROT    0                   /* Disable inter-task protection                                        */

// iperf tcp optimizations
#define TCP_MSS                 1460                /* Set Maximum Segment Size to 1460 bytes (Ethernet)                       */
#define TCP_WND                 (8 * TCP_MSS)       /* RX window: 8*MSS (~11.4KB); at 100M/1ms RTT the bandwidth-delay product ~12KB, so this already saturates the link */
#define TCP_SND_BUF             (8 * TCP_MSS)       /* TX buffer: 8*MSS (~11.4KB) avoids stalling under load               */
#define TCP_SND_QUEUELEN        ((4 * (TCP_SND_BUF) + (TCP_MSS - 1)) / (TCP_MSS)) /* segments allowed in send queue */
#define PBUF_POOL_SIZE          36                  /* Pbufs in the pool (~36*1554 = 56KB, fits in MEM_SIZE); absorbs 100M RX bursts */
#define MEMP_NUM_PBUF           56                  /* Number of PBUF structures                                            */
#define MEMP_NUM_TCP_SEG        56                  /* Number of TCP segments (raised from default for 100M sustained load)  */
#define MEMP_NUM_TCP_PCB        16                  /* Concurrent TCP PCBs                                                  */

/* lwiperf: raise the idle timeout far above any legitimate transfer so a
 * momentary gap in the data stream can never abort a long iperf session.
 * Capped at 255 (u8_t) -> ~255s of true idle tolerance. */
#define LWIPERF_TCP_MAX_IDLE_SEC 255U

#define ETH_PAD_SIZE            2                   /* Add 2 bytes before the Ethernet header to ensure payload alignment   */

#define __LWIP_DEBUG__                              /* Enable debugging through UART interface                              */

#define LWIP_NETIF_EXT_STATUS_CALLBACK  1           /* Enable an extended callback function for netif                       */

#ifdef __LWIP_DEBUG__
#define LWIP_DEBUG                                  /* Enable LwIP debugging                                                */
#endif

#ifndef IFX_LWIP_DEBUG
#define IFX_LWIP_DEBUG          LWIP_DBG_OFF        /* IFX LwIP debug level set to OFF                                      */
#endif
#define DHCP_DEBUG              LWIP_DBG_OFF        /* Enable DHCP Debug                                                    */
#define NETIF_DEBUG             LWIP_DBG_ON         /* Enable NETIF Debug                                                   */
#define LWIP_DBG_TYPES_ON       LWIP_DBG_STATE      /* Enable only module state debug messages                              */

#ifdef __GNUC__
    /* to avoid compiler error for double declaration we inform GNUC that ssize_t is declared by lwip */
    #define _SSIZE_T_DECLARED
#endif

#endif /* __LWIPOPTS_H__ */
