/**********************************************************************************************************************
 * \file UART_Logging.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "UART_Logging.h"
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "IfxStdIf_DPipe.h"
#include "IfxPort.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SERIAL_BAUDRATE         921600                                      /* Baud rate in bit/s                   */

#define SERIAL_PIN_RX           IfxAsclin4_RXA_P00_12_IN                     /* RX pin of the board                  */
#define SERIAL_PIN_TX           IfxAsclin4_TX_P00_9_OUT                     /* TX pin of the board                  */

#define INTPRIO_ASCLIN4_TX      29                                          /* Priority of the ISR                  */
#define INTPRIO_ASCLIN4_RX      30                                          /* Priority of the RX ISR               */
#define INTPRIO_ASCLIN4_ERR     31                                          /* Priority of the Error ISR            */

#define ASC_TX_BUFFER_SIZE      256                                         /* Definition of the buffer size        */
#define ASC_RX_BUFFER_SIZE      256                                         /* Definition of the RX buffer size     */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxStdIf_DPipe *g_uartDPipePtr = NULL_PTR;                                 /* Optional DPipe binding for legacy users */
IfxAsclin_Asc g_asc;                                                        /* Declaration of the ASC handle        */
uint8 g_ascTxBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];             /* Declaration of the FIFO parameters   */
static uint8 g_ascRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];      /* Declaration of the RX FIFO           */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(asclin4TxISR, 0, INTPRIO_ASCLIN4_TX);                     /* Adding the Interrupt Service Routine     */
IFX_INTERRUPT(asclin4RxISR, 0, INTPRIO_ASCLIN4_RX);
IFX_INTERRUPT(asclin4ErrISR, 0, INTPRIO_ASCLIN4_ERR);

void asclin4TxISR(void)
{
    if (g_uartDPipePtr != NULL_PTR)
    {
        IfxStdIf_DPipe_onTransmit(g_uartDPipePtr);
    }
    else
    {
        IfxAsclin_Asc_isrTransmit(&g_asc);
    }
}

void asclin4RxISR(void)
{
    if (g_uartDPipePtr != NULL_PTR)
    {
        IfxStdIf_DPipe_onReceive(g_uartDPipePtr);
    }
    else
    {
        IfxAsclin_Asc_isrReceive(&g_asc);
    }
}

void asclin4ErrISR(void)
{
    if (g_uartDPipePtr != NULL_PTR)
    {
        IfxStdIf_DPipe_onError(g_uartDPipePtr);
    }
    else
    {
        IfxAsclin_Asc_isrError(&g_asc);
    }
}

void initUART(void)
{
    /* Initialize an instance of IfxAsclin_Asc_Config with default values */
    IfxAsclin_Asc_Config ascConfig;
    IfxAsclin_Asc_initModuleConfig(&ascConfig, SERIAL_PIN_TX.module);

    /* High-speed UART: explicit 16x oversampling with center sampling. */
    ascConfig.baudrate.baudrate = SERIAL_BAUDRATE;
    ascConfig.baudrate.oversampling = IfxAsclin_OversamplingFactor_16;
    ascConfig.baudrate.prescaler = 1;
    ascConfig.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three;
    ascConfig.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_8;

    /* ISR priorities and interrupt target */
    ascConfig.interrupt.txPriority = INTPRIO_ASCLIN4_TX;
    ascConfig.interrupt.rxPriority = INTPRIO_ASCLIN4_RX;
    ascConfig.interrupt.erPriority = INTPRIO_ASCLIN4_ERR;
    ascConfig.interrupt.typeOfService = IfxCpu_Irq_getTos(IfxCpu_getCoreIndex());

    /* FIFO configuration */
    ascConfig.txBuffer = &g_ascTxBuffer;
    ascConfig.txBufferSize = ASC_TX_BUFFER_SIZE;
    ascConfig.rxBuffer = &g_ascRxBuffer;
    ascConfig.rxBufferSize = ASC_RX_BUFFER_SIZE;

    /* Port pins configuration */
    const IfxAsclin_Asc_Pins pins =
    {
        NULL_PTR,         IfxPort_InputMode_pullUp,                     /* CTS pin not used                         */
        &SERIAL_PIN_RX,   IfxPort_InputMode_pullUp,                     /* RX pin not used                          */
        NULL_PTR,         IfxPort_OutputMode_pushPull,                  /* RTS pin not used                         */
        &SERIAL_PIN_TX,   IfxPort_OutputMode_pushPull,                  /* TX pin                                   */
        IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    IfxAsclin_Asc_initModule(&g_asc, &ascConfig);                       /* Initialize module with above parameters  */
}

void sendUARTMessage(char * msg, Ifx_SizeT count)
{
    (void)IfxAsclin_Asc_write(&g_asc, msg, &count, 0);                  /* Non-blocking debug output                */
}

boolean initUARTConsole(IfxStdIf_DPipe *io)
{
    if (io == NULL_PTR)
    {
        return FALSE;
    }

    initUART();

    if (!IfxStdIf_DPipe_ascInit(io, &g_asc))
    {
        return FALSE;
    }

    g_uartDPipePtr = io;
    return TRUE;
}
