/**
 * \file netif.c
 * \brief Source file of lwIP low level and netif functions
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

/*
 * Copyright (c) 2001-2004 Swedish Institute of Computer Science.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * This file is part of the lwIP TCP/IP stack.
 *
 * Author: Adam Dunkels <adam@sics.se>
 *
 */

/**
 * This file is a skeleton for developing Ethernet network interface
 * drivers for lwIP. Add code to the low_level functions and do a
 * search-and-replace for the word "ethernetif" to replace it with
 * something that better describes your network interface.
 */

#include "lwip/opt.h"

#include "lwip/def.h"
#include "lwip/mem.h"
#include "lwip/pbuf.h"
#include <lwip/stats.h>
#include <lwip/snmp.h>
#include "netif/etharp.h"
#include "netif/ppp/pppoe.h"
#include "lwip/prot/ip4.h"

#include "IfxGeth_Eth.h"
#include "Ifx_Lwip.h"

/* Helper: check if an Ethernet frame contains a TCP segment suitable for TSO.
 * Uses lwIP protocol structs (already included via netif/etharp.h). */
static boolean is_tcp_segment(const uint8_t *frame, uint16_t len)
{
    struct eth_hdr *eth;
    struct ip_hdr  *iph;

    if (len < (SIZEOF_ETH_HDR + IP_HLEN))
        return FALSE;

    eth = (struct eth_hdr *)frame;
    if (htons(eth->type) != ETHTYPE_IP)
        return FALSE;

    iph = (struct ip_hdr *)(frame + SIZEOF_ETH_HDR);
    if (IPH_PROTO(iph) != 6)  /* IP_PROTO_TCP */
        return FALSE;

    return TRUE;
}
#include "Ifx_Netif.h"
#include "IfxGeth_Phy_Rtl8211f.h"
#include "Configuration.h"
#include <string.h>

/* Define those to better describe your network interface. */
#define IFNAME0 'e'
#define IFNAME1 'n'

/**
 * Helper struct to hold private data used to operate your ethernet interface.
 * Keeping the ethernet address of the MAC in this struct is not necessary
 * as it is already kept in the struct netif.
 * But this is only an example, anyway...
 */
struct ethernetif
{
    eth_addr_t *ethaddr;
    /* Add whatever per-interface state that is needed here. */
};

/* pin configuration RTL8211F */
const IfxGeth_Eth_RgmiiPins rtl8211f_pins = {
                                   .txClk = &ETH_TXCLK_PIN,     /* TXCLK */
                                   .txd0 = &ETH_TXD0_PIN,       /* TXD0 */
                                   .txd1 = &ETH_TXD1_PIN,       /* TXD1 */
                                   .txd2 = &ETH_TXD2_PIN,       /* TXD2 */
                                   .txd3 = &ETH_TXD3_PIN,       /* TXD3 */
		                           .txCtl = &ETH_TXCTL_PIN,     /* TXCTL */
		                           .rxClk = &ETH_RXCLK_PIN,     /* RXCLK */
                                   .rxd0 = &ETH_RXD0_PIN,       /* RXD0 */
								   .rxd1 = &ETH_RXD1_PIN,       /* RXD1 */
								   .rxd2 = &ETH_RXD2_PIN,       /* RXD2 */
								   .rxd3 = &ETH_RXD3_PIN,       /* RXD3 */
								   .rxCtl = &ETH_RXCTL_PIN,     /* RXCTL */
                                   .mdc = &ETH_MDC_PIN,         /* MDC */
                                   .mdio = &ETH_MDIO_PIN,       /* MDIO */
		                           .grefClk = &ETH_GREFCLK_PIN  /* GREFCLK */
};

/**
 * In this function, the hardware should be initialized.
 * Called from ethernetif_init().
 *
 * @param netif the already initialized lwip network interface structure
 *        for this ethernetif
 */
static void low_level_init(netif_t *netif)
{
    IfxGeth_Eth *ethernetif = netif->state;
    int     i;

    /* set MAC hardware address length */
    netif->hwaddr_len = ETHARP_HWADDR_LEN;

    /* set MAC hardware address */
    for (i = 0; i < ETHARP_HWADDR_LEN; i++)
    {
        netif->hwaddr[i] = g_Lwip.eth_addr.addr[i];
    }

    /* maximum transfer unit */
    netif->mtu = 1500;

    /* device capabilities */
    /* don't set NETIF_FLAG_ETHARP if this device is not an ethernet one */
    /* we don't set the LINK_UP flag because we don't say when it is linked */
    netif->flags = NETIF_FLAG_BROADCAST | NETIF_FLAG_ETHARP;

    /* Do whatever else is needed to initialize interface. */
    {
        IfxGeth_Eth_Config GethConfig;

        IfxGeth_Eth_initModuleConfig(&GethConfig, &MODULE_GETH);
        // this is our RTL8211F
        GethConfig.phyInterfaceMode = IfxGeth_PhyInterfaceMode_rgmii;
        GethConfig.pins.rgmiiPins = &rtl8211f_pins;
        GethConfig.mac.lineSpeed = IfxGeth_LineSpeed_1000Mbps;
        // MAC core configuration
        GethConfig.mac.loopbackMode = IfxGeth_LoopbackMode_disable;
        GethConfig.mac.macAddress[0] = netif->hwaddr[0];
        GethConfig.mac.macAddress[1] = netif->hwaddr[1];
        GethConfig.mac.macAddress[2] = netif->hwaddr[2];
        GethConfig.mac.macAddress[3] = netif->hwaddr[3];
        GethConfig.mac.macAddress[4] = netif->hwaddr[4];
        GethConfig.mac.macAddress[5] = netif->hwaddr[5];

        // MTL configuration
    GethConfig.mtl.numOfTxQueues = 1;
    GethConfig.mtl.numOfRxQueues = 1;
    GethConfig.mtl.txQueue[0].txQueueSize = IfxGeth_QueueSize_8192Bytes;
    GethConfig.mtl.txQueue[0].storeAndForward = TRUE;
    GethConfig.mtl.rxQueue[0].rxQueueSize = IfxGeth_QueueSize_8192Bytes;
        GethConfig.mtl.rxQueue[0].rxDmaChannelMap = IfxGeth_RxDmaChannel_0;
        GethConfig.mtl.rxQueue[0].storeAndForward = TRUE;

        GethConfig.dma.numOfTxChannels = 1;
        GethConfig.dma.numOfRxChannels = 1;
    GethConfig.dma.addressAlignedBeatsEnabled = TRUE;
    GethConfig.dma.fixedBurstEnabled = FALSE;
    GethConfig.dma.mixedBurstEnabled = TRUE;
        GethConfig.dma.txChannel[0].channelId = IfxGeth_TxDmaChannel_0;
        GethConfig.dma.txChannel[0].txDescrList = (IfxGeth_TxDescrList *)&lmu_txDescrList[0];
        GethConfig.dma.txChannel[0].txBuffer1StartAddress = (uint32 *)&channel0TxBuffer1[0][0]; // user buffer
    GethConfig.dma.txChannel[0].txBuffer1Size = IFXGETH_MAX_TX_BUFFER_SIZE; // used to calculate the next descriptor  buffer offset
    GethConfig.dma.txChannel[0].maxBurstLength = IfxGeth_DmaBurstLength_32;
    GethConfig.dma.txChannel[0].enableOSF = TRUE;

        GethConfig.dma.rxChannel[0].channelId = IfxGeth_RxDmaChannel_0;
        GethConfig.dma.rxChannel[0].rxDescrList = (IfxGeth_RxDescrList *)&lmu_rxDescrList[0];
        GethConfig.dma.rxChannel[0].rxBuffer1StartAddress = (uint32 *)&channel0RxBuffer1[0][0]; // user buffer
    GethConfig.dma.rxChannel[0].rxBuffer1Size = IFXGETH_MAX_RX_BUFFER_SIZE; // user defined variable
    GethConfig.dma.rxChannel[0].maxBurstLength = IfxGeth_DmaBurstLength_32;

        IfxSrc_Tos gethIsrProvider;

        if (CPU_WHICH_SERVICE_ETHERNET) gethIsrProvider = (IfxSrc_Tos)(CPU_WHICH_SERVICE_ETHERNET+1);
        else  gethIsrProvider = (IfxSrc_Tos)CPU_WHICH_SERVICE_ETHERNET;

        GethConfig.dma.txInterrupt[0].channelId = IfxGeth_DmaChannel_0;
        GethConfig.dma.txInterrupt[0].priority = ISR_PRIORITY_GETH_TX;    // priority
        GethConfig.dma.txInterrupt[0].provider = gethIsrProvider;
        GethConfig.dma.rxInterrupt[0].channelId = IfxGeth_DmaChannel_0;
        GethConfig.dma.rxInterrupt[0].priority = ISR_PRIORITY_GETH_RX;    // priority
        GethConfig.dma.rxInterrupt[0].provider = gethIsrProvider;

    	/* first we reset our phy manually, to make sure that the phy is ready when we init our module */
        {
        	IfxGeth_enableModule(&MODULE_GETH);
        	IfxPort_setPinModeOutput(ETH_MDC_PIN.pin.port, ETH_MDC_PIN.pin.pinIndex, IfxPort_OutputMode_pushPull, ETH_MDC_PIN.select);
            GETH_GPCTL.B.ALTI0  = ETH_MDIO_PIN.inSelect;

            while (GETH_MAC_MDIO_ADDRESS.B.GB) {};
            // first we wait that we are able to communicate with the Phy
            do
            {
            	GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) | (3 << 2) | (1 << 0);
                while (GETH_MAC_MDIO_ADDRESS.B.GB) {};
            } while (GETH_MAC_MDIO_DATA.U & 0x8000);                                                      // wait for reset to finish
            // reset PHY
            // put data
        	GETH_MAC_MDIO_DATA.U = 0x8000;
            GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) |  (1 << 2) | (1 << 0);
            while (GETH_MAC_MDIO_ADDRESS.B.GB) {};

            do
            {
            	GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) | (3 << 2) | (1 << 0);
                while (GETH_MAC_MDIO_ADDRESS.B.GB) {};
            } while (GETH_MAC_MDIO_DATA.U & 0x8000);                                                      // wait for reset to finish
        }

        // initialize the module
    	IfxGeth_Eth_initModule(ethernetif, &GethConfig);

   		IfxGeth_Eth_Phy_Rtl8211f_init();

    	// and enable transmitter/receiver
    	IfxGeth_Eth_startTransmitters(ethernetif, 1);
    	IfxGeth_Eth_startReceivers(ethernetif, 1);

    	// The ETH is ready for use now!
        /* we set the LINK_UP flag if we have a valid link */
    	if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSTS == 1)
    	{
    		// we have a valid link
    		netif->flags |= NETIF_FLAG_LINK_UP;
    		// we set the correct duplexMode
    		if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKMOD == 1)
    			IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
    		else
    			IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
    		// we set the correct speed
    		if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSPEED == 0)
    			// 10MBit speed
    			IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
    		else
        		if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSPEED == 1)
        			// 100MBit speed
        			IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
        		else
        			// 1000MBit speed
        			IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_1000Mbps);
    	}
    }
}

/**
 * This function should do the actual transmission of the packet. The packet is
 * contained in the pbuf that is passed to the function. This pbuf
 * might be chained.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @param p the MAC packet to send (e.g. IP packet including MAC addresses and type)
 * @return ERR_OK if the packet could be sent
 *         an err_t value if the packet couldn't be sent
 *
 * @note Returning ERR_MEM here if a DMA queue of your MAC is full can lead to
 *       strange results. You might consider waiting for space in the DMA queue
 *       to become availale since the stack doesn't retry to send a packet
 *       dropped because of memory failure (except for the TCP timers).
 */
static err_t low_level_output(netif_t *netif, pbuf_t *p)
{
    IfxGeth_Eth *ethernetif = netif->state;
    struct pbuf *q;
    u16_t length = p->tot_len;
    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output (p=%#x)\n", p));

    if ((p->type_internal == PBUF_REF) || (p->type_internal == PBUF_ROM))
    {
        IfxGeth_Eth_sendTransmitBuffer(ethernetif, p->tot_len, IfxGeth_TxDmaChannel_0);
    }
    else
    {
        /* Copy pbuf chain to contiguous DMA TX buffer */
        u8_t *tbuf = IfxGeth_Eth_waitTransmitBuffer(ethernetif, IfxGeth_TxDmaChannel_0);
        u16_t l    = 0;

        for (q = p; q != NULL; q = q->next)
        {
            memcpy((u8_t *)&tbuf[l], q->payload, q->len);
            l = l + q->len;
            LWIP_ASSERT("low_level_output: length overflow the buffer\n", (l < IFXGETH_MAX_TX_BUFFER_SIZE));
        }

        /* Check if TSO is beneficial: TCP segment larger than MSS.
         * TSO uses a context descriptor + data descriptor with TSE=1 and
         * TCP checksum offload (CIC_TPL=2). Hardware splits into MSS-sized
         * segments, dramatically reducing per-packet CPU overhead. */
        if ((l > TCP_MSS) && is_tcp_segment(tbuf, l))
        {
            volatile IfxGeth_TxDescr *ctxDesc;
            volatile IfxGeth_TxDescr *dataDesc;
            volatile IfxGeth_TxDescr *nextDescr;
            uint32  remaining, offset, chunk;
            uint8  *src;

            /* Copy the entire large frame to TSO scratch buffer (LMURAM, 48KB).
             * The regular DMA TX buffer is only 2576 bytes — too small for TSO. */
            memcpy(tso_tx_buffer, tbuf, l);

            /* Context descriptor: provides MSS for TSO hardware */
            ctxDesc = IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
            ctxDesc->TDES3.U         = 0;
            ctxDesc->TDES3.C.TCMSSV  = 1;
            ctxDesc->TDES3.C.CTXT    = 1;
            ctxDesc->TDES3.C.OWN     = 1;
            ctxDesc->TDES2.U         = 0;
            ctxDesc->TDES2.C.MSS     = TCP_MSS;
            ctxDesc->TDES0.U         = 0;
            IfxGeth_Eth_shuffleTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);

            /* Data descriptors: chain through the large TSO buffer.
             * Each descriptor points to a chunk of up to bufferLength bytes. */
            remaining = l;
            offset    = 0;
            src       = tso_tx_buffer;
            {
                uint32 bufferLength = ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txBuf1Size;
                uint32 numOfDesc    = remaining / bufferLength;
                if (remaining % bufferLength) numOfDesc++;
                uint32 di;
                for (di = 0; di < numOfDesc; di++)
                {
                    dataDesc = IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
                    chunk = (remaining > bufferLength) ? bufferLength : remaining;

                    dataDesc->TDES0.U     = (uint32)(src + offset);
                    dataDesc->TDES2.R.B1L = chunk;
                    dataDesc->TDES2.R.IOC = (di == (numOfDesc - 1)) ? 1 : 0;
                    dataDesc->TDES3.U     = 0;
                    if (di == 0)
                    {
                        dataDesc->TDES3.R.FL_TPL = l;  /* total frame length on first desc */
                    }
                    dataDesc->TDES3.R.TSE     = 1;
                    dataDesc->TDES3.R.CIC_TPL = 2;
                    dataDesc->TDES3.R.SAIC    = 0;
                    dataDesc->TDES3.R.CPC     = 0;
                    dataDesc->TDES3.R.FD      = (di == 0) ? 1 : 0;
                    dataDesc->TDES3.R.LD      = (di == (numOfDesc - 1)) ? 1 : 0;
                    dataDesc->TDES3.R.CTXT    = 0;
                    dataDesc->TDES3.R.OWN     = 1;

                    offset    += chunk;
                    remaining -= chunk;
                    IfxGeth_Eth_shuffleTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
                }
                nextDescr = IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
            }

            /* Trigger DMA transmission */
            IfxGeth_dma_setTxDescriptorTailPointer(ethernetif->gethSFR, IfxGeth_TxDmaChannel_0, (uint32)nextDescr);
            IfxGeth_Eth_wakeupTransmitter(ethernetif, IfxGeth_TxDmaChannel_0);
            ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txCount++;
            ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txDescrPtr = nextDescr;
        }
        else
        {
            /* Normal path: no TSO, standard checksum (CIC_TPL=3).
             * Fixup B1L then use standard send function. */
            IfxGeth_TxDescr *txd;
            txd = (IfxGeth_TxDescr *)IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
            txd->TDES2.R.B1L = IFXGETH_MAX_TX_BUFFER_SIZE;
            IfxGeth_Eth_sendTransmitBuffer(ethernetif, l, IfxGeth_TxDmaChannel_0);
        }
    }

    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output: signal length: %d\n", length));
    LINK_STATS_INC(link.xmit);
    return ERR_OK;
}

static uint16 GetRxFrameSize(IfxGeth_RxDescr *descr)
{
  uint16 len;

  uint32 rdes3 = descr->RDES3.U;
  uint32 rdes1 = descr->RDES1.U;

  if (((rdes3 & (1UL << 15)) != 0U) ||
      ((rdes1 & (1UL << 7)) != 0U) ||
      ((rdes3 & (1UL << 28)) == 0U))
  {
    /* Error, this block is invalid */
    len = 0xFFFFU;
  }
  else
  {
    /* Subtract CRC */
    len = (uint16)((rdes3 & 0x7FFF) - 4U);
  }

  return len;
}

/**
 * Should allocate a pbuf and transfer the bytes of the incoming
 * packet from the interface into the pbuf.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return a pbuf filled with the received packet (including MAC header)
 *         NULL on memory error
 */
static pbuf_t *low_level_input(netif_t *netif)
{
    IfxGeth_Eth *ethernetif = netif->state;
    pbuf_t *p;
    u16_t   len;

    len = 0;
    if (IfxGeth_Eth_isRxDataAvailable(ethernetif, IfxGeth_RxDmaChannel_0) != FALSE)
    {
        len = GetRxFrameSize((IfxGeth_RxDescr *)IfxGeth_Eth_getActualRxDescriptor(ethernetif, IfxGeth_RxDmaChannel_0));
    }

    if (len == 0)
    {
        return NULL;
    }

    /* Error frame — release DMA buffer and return NULL */
    if (len == 0xFFFFU)
    {
        IfxGeth_Eth_freeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);
        return NULL;
    }

    /* Zero-copy RX: use PBUF_REF pointing directly to DMA buffer.
     * The DMA buffer is released in ifx_netif_input after lwIP processes the packet. */
    p = pbuf_alloc(PBUF_RAW, 0, PBUF_REF);

    if (p != NULL)
    {
        u8_t *src = IfxGeth_Eth_getReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);
        p->payload = src;
        p->len     = len;
        p->tot_len = len;

        LINK_STATS_INC(link.recv);
    }
    else
    {
        /* Out of pbuf headers — release the DMA buffer so we don't stall */
        IfxGeth_Eth_freeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);
        LINK_STATS_INC(link.memerr);
        LINK_STATS_INC(link.drop);
    }

    return p;
}


/**
 * This function should be called when a packet is ready to be read
 * from the interface. It uses the function low_level_input() that
 * should handle the actual reception of bytes from the network
 * interface. Then the type of the received packet is determined and
 * the appropriate input function is called.
 *
 * @param netif the lwip network interface structure for this ethernetif
 */
err_t ifx_netif_input(netif_t *netif)
{
    IfxGeth_Eth *ethernetif = netif->state;
    eth_hdr_t *ethhdr;
    pbuf_t    *p;

    /* move received packet into a new pbuf */
    p = low_level_input(netif);

    /* no packet could be read, silently ignore this */
    if (p == NULL)
    {
        return ERR_OK;
    }

    /* points to packet payload, which starts with an Ethernet header */
    ethhdr = p->payload;

    switch (htons(ethhdr->type))
    {
    /* IP or ARP packet? */
    case ETHTYPE_IP:
    case ETHTYPE_ARP:
#if PPPOE_SUPPORT
    case ETHTYPE_PPPOEDISC:
    case ETHTYPE_PPPOE:
#endif /* PPPOE_SUPPORT */
        /* full packet send to tcpip_thread to process */
        if (netif->input(p, netif) != ERR_OK)
        {
            LWIP_DEBUGF(NETIF_DEBUG, ("ifx_netif_input: IP input error\n"));
            pbuf_free(p);
        }
        break;

    default:
        LWIP_DEBUGF(NETIF_DEBUG, ("ifx_netif_input: type unknown\n"));
        pbuf_free(p);
        break;
    }

    /* Release DMA buffer back to hardware.
     * Since ETH_PAD_SIZE=0 and we use PBUF_REF, the DMA buffer is not
     * owned by the pbuf. lwIP has finished processing by now (NO_SYS=1,
     * synchronous path), so it's safe to release. */
    IfxGeth_Eth_freeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);

    return ERR_OK;
}


/**
 * Should be called at the beginning of the program to set up the
 * network interface. It calls the function low_level_init() to do the
 * actual setup of the hardware.
 *
 * This function should be passed as a parameter to netif_add().
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return ERR_OK if the loopif is initialized
 *         ERR_MEM if private data couldn't be allocated
 *         any other err_t on error
 */
err_t ifx_netif_init(netif_t *netif)
{
    IfxGeth_Eth *ethernetif;

    LWIP_ASSERT("netif != NULL", (netif != NULL));
    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("ifx_netif_init ( %#x)\n", netif));

    ethernetif = IfxGeth_get();

    if (ethernetif == NULL)
    {
        LWIP_DEBUGF(NETIF_DEBUG, ("ifx_netif_init: out of memory\n"));
        return ERR_MEM;
    }

#if LWIP_NETIF_HOSTNAME
    /* Initialize interface hostname */
    netif->hostname = "lwip";
#endif /* LWIP_NETIF_HOSTNAME */

    /*
     * Initialize the snmp variables and counters inside the struct netif.
     * The last argument should be replaced with your link speed, in units
     * of bits per second.
     */
    //NETIF_INIT_SNMP(netif, snmp_ifType_ethernet_csmacd, LINK_SPEED_OF_YOUR_NETIF_IN_BPS);

    netif->state      = ethernetif;
    netif->name[0]    = IFNAME0;
    netif->name[1]    = IFNAME1;
    /* We directly use etharp_output() here to save a function call.
     * You can instead declare your own function an call etharp_output()
     * from it if you have to do some checks before sending (e.g. if link
     * is available...) */
    netif->output     = etharp_output;
    netif->linkoutput = low_level_output;

    /* initialize the hardware */
    low_level_init(netif);

    return ERR_OK;
}
