/**
 * \file Ifx_Lwip.c
 * \brief Source file of lwIP port to TriCore
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include <Cpu/Std/Ifx_Types.h>
#include <Cpu/Std/IfxCpu.h>
#include "IfxGeth_Eth.h"
#include "Ifx_Lwip.h"
#include "lwipopts.h"
#include "Ifx_Netif.h"
#include "IfxGeth_Phy_Rtl8211f.h"
#include "Configuration.h"
#include <string.h>
#include <stdarg.h>
#include <UART_Logging.h>


/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/
#define IFX_LWIP_TIMER_TICK_MS      (1U)    // number of timer ticks per millisecond

#define IFX_LWIP_ARP_PERIOD         (ARP_TMR_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_TCP_FAST_PERIOD    (TCP_FAST_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_TCP_SLOW_PERIOD    (TCP_SLOW_INTERVAL / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_DHCP_COARSE_PERIOD (DHCP_COARSE_TIMER_MSECS / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_DHCP_FINE_PERIOD   (DHCP_FINE_TIMER_MSECS / IFX_LWIP_TIMER_TICK_MS)
#define IFX_LWIP_LINK_PERIOD        (100U / IFX_LWIP_TIMER_TICK_MS) /* 100 ms */

#define IFX_LWIP_FLAG_ARP           (1U << 1)
#define IFX_LWIP_FLAG_TCP_FAST      (1U << 2)
#define IFX_LWIP_FLAG_TCP_SLOW      (1U << 3)
#define IFX_LWIP_FLAG_LINK          (1U << 4)
#define IFX_LWIP_FLAG_DHCP_COARSE   (1U << 5)
#define IFX_LWIP_FLAG_DHCP_FINE     (1U << 6)

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/* ===== Memory layout (performance critical!) =====
 * GETH DMA shared data (descriptors + frame buffers) lives in LMURAM.
 *
 * Rationale (measured): with the buffers in CPU0 DSPR the GETH DMA has to
 * reach them over SRI through the core's slave port, where it arbitrates
 * against the core itself. The DMA then cannot drain the 8KB MTL RX FIFO
 * fast enough and the MAC throttles the link with 802.3x PAUSE frames even
 * while the CPU sits 70% idle (~21k pause frames per 6s at 550Mbps).
 * LMURAM is a plain SRI slave with full burst bandwidth and no core
 * contention, so the DMA runs at line rate.
 *
 * The CPU still needs fast access to the RX payload, so it reads the frames
 * through the CACHED LMU view (0x9xxxxxxx) after invalidating the lines the
 * DMA just overwrote; descriptors are touched through the NON-CACHED view
 * (0xBxxxxxxx) so ownership flags are always coherent (see netif.c).
 *
 * The lwIP heap is CPU-only, so it stays in zero-waitstate DSPR0. */

#if defined(__TASKING__)
#pragma section fardata "lmudata"
#pragma section farbss "lmubss"
#elif defined(__GNUC__)
#pragma section ".lmudata" aw
#endif

/* Multi-core spinlock */
volatile uint32 lwip_global_lock = 0;

#if defined(__GNUC__)
#pragma section
#pragma section ".lmubss" aw
#endif

/* DMA descriptor lists in LMURAM */
IfxGeth_RxDescrList lmu_rxDescrList[IFXGETH_NUM_MODULES][IFXGETH_NUM_RX_CHANNELS];
IfxGeth_TxDescrList lmu_txDescrList[IFXGETH_NUM_MODULES][IFXGETH_NUM_TX_CHANNELS];

/* DMA frame buffers in LMURAM.
 * 64-byte aligned so that the per-frame cache invalidation done before the
 * RX copy (netif.c) never covers a neighbouring row: the 1536-byte row
 * stride is a multiple of the 32-byte cache line. */
IFX_ALIGN(64) uint8 channel0TxBuffer1[IFXGETH_MAX_TX_DESCRIPTORS][IFXGETH_MAX_TX_BUFFER_SIZE];
IFX_ALIGN(64) uint8 channel0RxBuffer1[IFXGETH_MAX_RX_DESCRIPTORS][IFXGETH_MAX_RX_BUFFER_SIZE];

/* TSO scratch buffer for oversized TCP segments (payload > MSS).
 * lwIP sends MSS-sized segments, so the TSO path is inert for iperf. */
#define TSO_TX_BUFFER_SIZE  (4 * 1024)
uint8 tso_tx_buffer[TSO_TX_BUFFER_SIZE];

#if defined(__GNUC__)
#pragma section
#endif

/* Back to DSPR0 for the CPU-only data */
#if defined(__TASKING__)
#pragma section fardata "data_cpu0"
#pragma section farbss "bss_cpu0"
#elif defined(__GNUC__)
#pragma section ".bss_cpu0" aw
#endif

/* lwIP memory heap: CPU-only (DMA never touches pbuf RAM — TX copies into
 * DMA buffers, RX copies out of DMA buffers). Zero-waitstate DSPR0.
 * Must be >= MEM_SIZE_ALIGNED + 2*SIZEOF_STRUCT_MEM. */
#define LWIP_LMURAM_HEAP_SIZE    (84 * 1024)
uint8 lwip_lmuram_heap[LWIP_LMURAM_HEAP_SIZE];

/* GETH driver handle: CPU-only software state (never accessed by DMA),
 * lives in fast core0 DSPR (single-core servicing, see
 * CPU_WHICH_SERVICE_ETHERNET == 0). */
IfxGeth_Eth g_IfxGeth;

/* Timer/counter (not shared) */
volatile uint32 g_TickCount_1ms;
Ifx_Lwip    g_Lwip;
uint32 isrTxCount=0;
uint32 isrRxCount=0;

#if defined(__GNUC__)
#pragma section
#endif

#if CPU_WHICH_SERVICE_ETHERNET == 0
    #if defined(__GNUC__)
    #pragma section ".text_cpu0" ax
    #endif
    #if defined(__TASKING__)
    #pragma section code    "text_cpu0"
    #pragma section farbss  "bss_cpu0"
    #pragma section fardata "data_cpu0"
    #endif
    #if defined(__DCC__)
    #pragma section CODE ".text_cpu0"
    #pragma section DATA ".data_cpu0" ".bss_cpu0" far-absolute RW
    #endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu0"
    #pragma ghs section bss= ".bss_cpu0"
    #pragma ghs section data=".data_cpu0"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 1) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
    #if defined(__GNUC__)
    #pragma section ".text_cpu1" ax
    #pragma section ".bss_cpu1" awc1
    #endif
    #if defined(__TASKING__)
    #pragma section code    "text_cpu1"
    #pragma section farbss  "bss_cpu1"
    #pragma section fardata "data_cpu1"
    #endif
    #if defined(__DCC__)
    #pragma section CODE ".text_cpu1"
    #pragma section DATA ".data_cpu1" ".bss_cpu1" far-absolute RW
    #endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu1"
    #pragma ghs section bss= ".bss_cpu1"
    #pragma ghs section data=".data_cpu1"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 2) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
    #if defined(__GNUC__)
    #pragma section ".text_cpu2" ax
    #pragma section ".bss_cpu2" awc2
    #endif
    #if defined(__TASKING__)
    #pragma section code    "text_cpu2"
    #pragma section farbss  "bss_cpu2"
    #pragma section fardata "data_cpu2"
    #endif
    #if defined(__DCC__)
    #pragma section CODE ".text_cpu2"
    #pragma section DATA ".data_cpu2" ".bss_cpu2" far-absolute RW
    #endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu2"
    #pragma ghs section bss= ".bss_cpu2"
    #pragma ghs section data=".data_cpu2"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 3) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
	#if defined(__GNUC__)
    #pragma section ".text_cpu3" ax
	#pragma section ".bss_cpu3" awc3
	#endif
	#if defined(__TASKING__)
    #pragma section code    "text_cpu3"
    #pragma section farbss  "bss_cpu3"
    #pragma section fardata "data_cpu3"
	#endif
	#if defined(__DCC__)
    #pragma section CODE ".text_cpu3"
	#pragma section DATA ".data_cpu3" ".bss_cpu3" far-absolute RW
	#endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu3"
    #pragma ghs section bss= ".bss_cpu3"
    #pragma ghs section data=".data_cpu3"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 4) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
	#if defined(__GNUC__)
    #pragma section ".text_cpu4" ax
	#pragma section ".bss_cpu4" awc4
	#endif
	#if defined(__TASKING__)
    #pragma section code    "text_cpu4"
    #pragma section farbss  "bss_cpu4"
    #pragma section fardata "data_cpu4"
	#endif
	#if defined(__DCC__)
    #pragma section CODE ".text_cpu4"
	#pragma section DATA ".data_cpu4" ".bss_cpu4" far-absolute RW
	#endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu4"
    #pragma ghs section bss= ".bss_cpu4"
    #pragma ghs section data=".data_cpu4"
    #endif
#elif ((CPU_WHICH_SERVICE_ETHERNET == 5) && (CPU_WHICH_SERVICE_ETHERNET < IFXCPU_NUM_MODULES))
	#if defined(__GNUC__)
    #pragma section ".text_cpu5" ax
	#pragma section ".bss_cpu5" awc5
	#endif
	#if defined(__TASKING__)
    #pragma section code    "text_cpu5"
    #pragma section farbss  "bss_cpu5"
    #pragma section fardata "data_cpu5"
	#endif
	#if defined(__DCC__)
    #pragma section CODE ".text_cpu5"
	#pragma section DATA ".data_cpu5" ".bss_cpu5" far-absolute RW
	#endif
    #if defined(__ghs__)
    #pragma ghs section text=".text_cpu5"
    #pragma ghs section bss= ".bss_cpu5"
    #pragma ghs section data=".data_cpu5"
    #endif
#else
#error "Set CPU_WHICH_SERVICE_ETHERNET to a valid value!"
#endif

/* Note: g_IfxGeth, channel0TxBuffer1, channel0RxBuffer1 are now in LMURAM
 * (defined above before the CPU-specific section pragmas). */


/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/
#if defined(__GNUC__)
    #pragma section // end bss section
#endif

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

#define Ifx_Lwip_timerIncr(var, PERIOD, FLAG) \
    {                                         \
        var += 1;                             \
        if (var >= PERIOD)                    \
        {                                     \
            var         = 0;                  \
            timerFlags |= FLAG;               \
        }                                     \
    }

/** \brief Timer interrupt callback */
void Ifx_Lwip_onTimerTick(void)
{
    Ifx_Lwip *lwip       = &g_Lwip;
    uint16    timerFlags = lwip->timerFlags;

    Ifx_Lwip_timerIncr(lwip->timer.arp, IFX_LWIP_ARP_PERIOD, IFX_LWIP_FLAG_ARP);

    Ifx_Lwip_timerIncr(lwip->timer.tcp_fast, IFX_LWIP_TCP_FAST_PERIOD, IFX_LWIP_FLAG_TCP_FAST);
    Ifx_Lwip_timerIncr(lwip->timer.tcp_slow, IFX_LWIP_TCP_SLOW_PERIOD, IFX_LWIP_FLAG_TCP_SLOW);

#if LWIP_DHCP
    Ifx_Lwip_timerIncr(lwip->timer.dhcp_coarse, IFX_LWIP_DHCP_COARSE_PERIOD, IFX_LWIP_FLAG_DHCP_COARSE);
    Ifx_Lwip_timerIncr(lwip->timer.dhcp_fine, IFX_LWIP_DHCP_FINE_PERIOD, IFX_LWIP_FLAG_DHCP_FINE);
#endif

    Ifx_Lwip_timerIncr(lwip->timer.link, IFX_LWIP_LINK_PERIOD, IFX_LWIP_FLAG_LINK);

    lwip->timerFlags = timerFlags;
}


/** \brief Polling the timer event flags */
void Ifx_Lwip_pollTimerFlags(void)
{
    Ifx_Lwip *lwip = &g_Lwip;
    uint16    timerFlags;

    /* disable interrupts */
    boolean interruptState = IfxCpu_disableInterrupts();

    timerFlags       = lwip->timerFlags;
    lwip->timerFlags = 0;

    /* NOTE: interrupts stay disabled while running the lwIP timer functions:
     * the RX ISR calls into the (non re-entrant) lwIP core, so tcp timers
     * must not run concurrently. All handlers below are short (<<100us);
     * the 32-entry RX ring absorbs line-rate bursts of ~390us. */

#if LWIP_DHCP
    if (timerFlags & IFX_LWIP_FLAG_DHCP_COARSE)
    {
        /* only if we have a link we will check the dhcp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
            dhcp_coarse_tmr();
    }

    if (timerFlags & IFX_LWIP_FLAG_DHCP_FINE)
    {
        /* only if we have a link we will check the dhcp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
            dhcp_fine_tmr();
    }
#endif

    if (timerFlags & IFX_LWIP_FLAG_TCP_FAST)
    {
        /* only if we have a link we will check the tcp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
            tcp_fasttmr();
    }

    if (timerFlags & IFX_LWIP_FLAG_TCP_SLOW)
    {
        /* only if we have a link we will check the tcp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
            tcp_slowtmr();
    }

    if (timerFlags & IFX_LWIP_FLAG_ARP)
    {
        /* only if we have a link we will check the arp */
        if (g_Lwip.netif.flags & NETIF_FLAG_LINK_UP)
            etharp_tmr();
    }

    if (timerFlags & IFX_LWIP_FLAG_LINK)
    {
        static uint8 prevLinkUp = 0xFF; /* 0xFF forces a report on the first poll */
        Ifx_GETH_MAC_PHYIF_CONTROL_STATUS ctrl_status;
        ctrl_status.U = GETH_MAC_PHYIF_CONTROL_STATUS.U;
        uint8 linkUp = (ctrl_status.B.LNKSTS == 0) ? 0 : 1;
        if (linkUp != prevLinkUp)
        {
            prevLinkUp = linkUp;
            if (linkUp == 0)
            {
                netif_set_link_down(&g_Lwip.netif);
                Ifx_Lwip_printf("LINK   : DOWN");
            }
            else
            {
                IfxGeth_Eth *ethernetif = g_Lwip.netif.state;
                const char *speedStr;
                const char *duplexStr;

                /* configure the MAC duplex mode from the PHY status */
                if (ctrl_status.B.LNKMOD == 1)
                {
                    IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
                    duplexStr = "full";
                }
                else
                {
                    IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
                    duplexStr = "half";
                }

                /* configure the MAC line speed from the PHY status */
                if (ctrl_status.B.LNKSPEED == 0)
                {
                    IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
                    speedStr = "10M";
                }
                else if (ctrl_status.B.LNKSPEED == 1)
                {
                    IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
                    speedStr = "100M";
                }
                else
                {
                    IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_1000Mbps);
                    speedStr = "1000M";
                }

                netif_set_link_up(&g_Lwip.netif);
                Ifx_Lwip_printf("LINK   : UP   %s %s-duplex", speedStr, duplexStr);
            }
        }
    }

    /* enable interrupts again */
    IfxCpu_restoreInterrupts(interruptState);
}


/** \brief Acquire the multi-core spinlock (LMURAM).
 *  Uses IfxCpu_setSpinLock for atomic test-and-set.
 *  Busy-waits until lock is acquired. */
void Ifx_Lwip_lock(void)
{
    while (IfxCpu_setSpinLock((IfxCpu_spinLock *)&lwip_global_lock, 0xFFFFFFFFu) == FALSE)
    {
        /* spin */
    }
}

/** \brief Release the multi-core spinlock */
void Ifx_Lwip_unlock(void)
{
    IfxCpu_resetSpinLock((IfxCpu_spinLock *)&lwip_global_lock);
}


/** \brief Polling the ETH receive event flags (original Infineon behavior).
 *  Added as a safety net alongside the RX ISR. */
/* Main-loop stall watchdog: tracks the largest gap between two consecutive
 * polls (STM ticks). A large max gap means something blocked the main loop
 * long enough to overflow the RX ring. */
volatile uint32 g_prof_poll_gap_max = 0;
volatile uint32 g_prof_poll_gap_1ms = 0;   /* gaps > 1 ms */
volatile uint32 g_diag_rbu = 0;            /* receive-buffer-unavailable events */
volatile uint32 g_prof_busy_ticks = 0;     /* STM ticks spent draining the RX ring */
volatile uint32 g_prof_idle_polls = 0;     /* polls that found an empty ring */

void Ifx_Lwip_pollReceiveFlags(void)
{
    static uint32 s_lastPoll = 0;
    uint32 now = IfxStm_getLower(&MODULE_STM0);

    if (s_lastPoll != 0)
    {
        uint32 gap = now - s_lastPoll;
        if (gap > g_prof_poll_gap_max)
        {
            g_prof_poll_gap_max = gap;
        }
        if (gap > IFX_CFG_STM_TICKS_PER_MS)
        {
            g_prof_poll_gap_1ms++;
        }
    }

    int max_pkts = 64;
    if (IfxGeth_Eth_isRxDataAvailable(&g_IfxGeth, IfxGeth_RxDmaChannel_0) == FALSE)
    {
        g_prof_idle_polls++;
    }
    else
    {
        uint32 tb = IfxStm_getLower(&MODULE_STM0);
        do
        {
            ifx_netif_input(&g_Lwip.netif);
        } while ((max_pkts-- > 0) && (IfxGeth_Eth_isRxDataAvailable(&g_IfxGeth, IfxGeth_RxDmaChannel_0) != FALSE));
        g_prof_busy_ticks += (IfxStm_getLower(&MODULE_STM0) - tb);
    }

    /* If the RX DMA ran out of descriptors (RBU) it may suspend and silently
     * drop frames at the FIFO. Detect, count and kick it back to life. */
    if (MODULE_GETH.DMA_CH[0].STATUS.U & (1u << 7)) /* RBU (W1C) */
    {
        g_diag_rbu++;
        MODULE_GETH.DMA_CH[0].STATUS.U = (1u << 7);
        IfxGeth_Eth_wakeupReceiver(&g_IfxGeth, IfxGeth_RxDmaChannel_0);
    }

    s_lastPoll = IfxStm_getLower(&MODULE_STM0);
}

#if LWIP_NETIF_EXT_STATUS_CALLBACK
static netif_ext_callback_t g_extCallback;

void netif_state_changed(struct netif* netif, netif_nsc_reason_t reason, const netif_ext_callback_args_t* args) {
    if(reason | LWIP_NSC_IPV4_ADDRESS_CHANGED) {
        LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE | LWIP_DBG_STATE, ("netif: new ip address assigned: %"U16_F".%"U16_F".%"U16_F".%"U16_F"\n",
                        ip4_addr1_16(netif_ip4_addr(netif)),
                        ip4_addr2_16(netif_ip4_addr(netif)),
                        ip4_addr3_16(netif_ip4_addr(netif)),
                        ip4_addr4_16(netif_ip4_addr(netif))));
    }

}
#endif

//________________________________________________________________________________________
// INITIALIZATION FUNCTION

/** \brief LWIP initialization function
 *
 * The followings are executed: */
void Ifx_Lwip_init(eth_addr_t ethAddr)
{
#ifdef __LWIP_DEBUG__
    //Init uart for debugging
    initUART();
#endif
    ip_addr_t default_ipaddr, default_netmask, default_gw;
    IP4_ADDR(&default_gw, 0,0,0,0);
    IP4_ADDR(&default_ipaddr, 0,0,0,0);
    IP4_ADDR(&default_netmask, 255,0,0,0);

    LWIP_DEBUGF(IFX_LWIP_DEBUG, ("Ifx_Lwip_init start!\n"));

    /** - initialise LWIP (lwip_init()) */
    lwip_init();

    /** - initialise and add a \ref netif */
    g_Lwip.eth_addr = ethAddr;
    netif_add(&g_Lwip.netif, &default_ipaddr, &default_netmask, &default_gw,
        (void *)0, ifx_netif_init, ethernet_input);
    netif_set_default(&g_Lwip.netif);
    netif_set_up(&g_Lwip.netif);

#if LWIP_NETIF_HOSTNAME
    g_Lwip.netif.hostname = BOARDNAME;
#endif

#if LWIP_DHCP
    /** - assign \ref dhcp to \ref netif */
    dhcp_set_struct(&g_Lwip.netif, &g_Lwip.dhcp);

    /* we start the dhcp always here also when we don't have a link here */
    dhcp_start(&g_Lwip.netif);
#endif

#if LWIP_NETIF_EXT_STATUS_CALLBACK
    netif_add_ext_callback(&g_extCallback, netif_state_changed);
#endif
    LWIP_DEBUGF(IFX_LWIP_DEBUG, ("Ifx_Lwip_init end!\n"));
}

void Ifx_Lwip_init_with_ip(eth_addr_t ethAddr, ip_addr_t ipAddr, ip_addr_t netMask, ip_addr_t gateway)
{
#ifdef __LWIP_DEBUG__
    //Init uart for debugging
    initUART();
#endif
    LWIP_DEBUGF(IFX_LWIP_DEBUG, ("Ifx_Lwip_init_with_ip start!\n"));

    /** - initialise LWIP (lwip_init()) */
    lwip_init();

    /** - initialise and add a \ref netif */
    g_Lwip.eth_addr = ethAddr;
    netif_add(&g_Lwip.netif, &ipAddr, &netMask, &gateway,
        (void *)0, ifx_netif_init, ethernet_input);
    netif_set_default(&g_Lwip.netif);
    netif_set_up(&g_Lwip.netif);

    Ifx_Lwip_printf("\r\nLWIP   : MAC %02X:%02X:%02X:%02X:%02X:%02X",
        ethAddr.addr[0], ethAddr.addr[1], ethAddr.addr[2],
        ethAddr.addr[3], ethAddr.addr[4], ethAddr.addr[5]);
    Ifx_Lwip_printf("LWIP   : IP  %s", ipaddr_ntoa(&ipAddr));
    Ifx_Lwip_printf("LWIP   : NM  %s", ipaddr_ntoa(&netMask));
    Ifx_Lwip_printf("LWIP   : GW  %s", ipaddr_ntoa(&gateway));

#if LWIP_NETIF_HOSTNAME
    g_Lwip.netif.hostname = BOARDNAME;
#endif

#if LWIP_DHCP
    /** - assign \ref dhcp to \ref netif */
    dhcp_set_struct(&g_Lwip.netif, &g_Lwip.dhcp);

    /* we start the dhcp always here also when we don't have a link here */
    dhcp_start(&g_Lwip.netif);
#endif

#if LWIP_NETIF_EXT_STATUS_CALLBACK
    netif_add_ext_callback(&g_extCallback, netif_state_changed);
#endif
    LWIP_DEBUGF(IFX_LWIP_DEBUG, ("Ifx_Lwip_init end!\n"));
}

/** Returns the current time in milliseconds,
 * may be the same as sys_jiffies or at least based on it. */
inline u32_t sys_now(void)
{
	return g_TickCount_1ms;
}

/**
 * This interrupt is raised by the ethernet tx. The initialization is done by IfxGeth_Eth_init().
 *
 * \isrProvider \ref ISR_PROVIDER_ETH
 * \isrPriority \ref ISR_PRIORITY_GETH_TX
 *
 */
IFX_INTERRUPT(ISR_Geth_Tx, CPU_WHICH_SERVICE_ETHERNET, ISR_PRIORITY_GETH_TX)
{
    isrTxCount++;

    /* DMA_CH0_STATUS bits are write-1-clear. TI (bit 0) and NIS (bit 15)
     * MUST be cleared here, otherwise the GETH keeps its interrupt request
     * line asserted and this ISR re-fires forever (interrupt storm that
     * starves the STM tick and the main loop). */
    MODULE_GETH.DMA_CH[0].STATUS.U = ((1u << 0) | (1u << 15));
}

/**
 * This interrupt is raised by the ethernet rx. The initialization is done by IfxGeth_Eth_init().
 *
 * \isrProvider \ref ISR_PROVIDER_ETH
 * \isrPriority \ref ISR_PRIORITY_GETH_RX
 *
 */
IFX_INTERRUPT(ISR_Geth_Rx, CPU_WHICH_SERVICE_ETHERNET, ISR_PRIORITY_GETH_RX)
{
    isrRxCount++;

    /* DMA_CH0_STATUS bits are write-1-clear. RI (bit 6) and NIS (bit 15)
     * MUST be cleared, otherwise the GETH keeps its interrupt request line
     * asserted and this ISR re-fires forever (interrupt storm that starves
     * the STM tick and the main loop -> throughput collapse).
     *
     * NOTE: no lwIP calls here. The lwIP core is not reentrant; packets are
     * drained from the RX ring by Ifx_Lwip_pollReceiveFlags() in the main
     * loop, which spins fast enough to keep up with line rate. */
    MODULE_GETH.DMA_CH[0].STATUS.U = ((1u << 6) | (1u << 15));
}

//________________________________________________________________________________________
// DEBUGGING FUNCTIONS
#include "Configuration.h"
#include <stdio.h>
#include <string.h>

#define MAXCHARS 256

s8_t Ifx_Lwip_printf(const char *format, ...)
{
#ifdef __LWIP_DEBUG__
    char    str[MAXCHARS + 4];
    s8_t    result = ERR_CONN;

    va_list args;
    va_start(args, format);
    vsnprintf(str, MAXCHARS, format, args);
    va_end(args);
    {
        Ifx_SizeT cnt = 0;
        while(str[cnt]!=0)
            cnt++;
        sendUARTMessage(str, cnt);
        sendUARTMessage("\r\n", 2);
    }
#endif
    return result;
}

#if defined(__GNUC__)
#pragma section // end text section
#endif
#if defined(__TASKING__)
#pragma section code restore
#pragma section fardata restore
#pragma section farbss restore
#endif
#if defined(__DCC__)
#pragma section CODE
#pragma section DATA RW
#endif
#if defined(__ghs__)
#pragma ghs section text=default
#pragma ghs section data=default
#pragma ghs section bss=default
#endif

