/**
 * \file netif.c
 * \brief Source file of lwIP low level and netif functions
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

/*
 * Copyright (c) 2001-2004 Swedish Institute of Computer Science.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
 * OF SUCH DAMAGE.
 *
 * This file is part of the lwIP TCP/IP stack.
 *
 * Author: Adam Dunkels <adam@sics.se>
 *
 */

/**
 * This file is a skeleton for developing Ethernet network interface
 * drivers for lwIP. Add code to the low_level functions and do a
 * search-and-replace for the word "ethernetif" to replace it with
 * something that better describes your network interface.
 */

#include "lwip/opt.h"

#include "lwip/def.h"
#include "lwip/mem.h"
#include "lwip/pbuf.h"
#include <lwip/stats.h>
#include <lwip/snmp.h>
#include "netif/etharp.h"
#include "netif/ppp/pppoe.h"
#include "lwip/prot/ip4.h"

#include "IfxGeth_Eth.h"
#include "Ifx_Lwip.h"

/* Addresses shared with the GETH DMA (descriptors + buffers) must never be
 * accessed through the CPU data cache. DSPR (0x7...) is scratchpad and
 * always coherent. LMU segment 9 (0x9...) is cacheable, so remap it to the
 * non-cached segment B view (0xB...). Identity for all other segments. */
#define GETH_DMA_ADDR(addr) \
    (((((uint32)(addr)) & 0xF0000000u) == 0x90000000u) \
         ? (void *)(((uint32)(addr)) | 0x20000000u)    \
         : (void *)(addr))

/* Inverse of GETH_DMA_ADDR: non-cached LMU view (0xB...) -> cached view
 * (0x9...). Reading the RX payload through the cached view turns the copy
 * into 256-bit SRI burst line fills instead of word-by-word uncached reads.
 * Identity for DSPR/other segments. */
#define GETH_CACHED_ADDR(addr) \
    (((((uint32)(addr)) & 0xF0000000u) == 0xB0000000u) \
         ? (void *)(((uint32)(addr)) & ~0x20000000u)   \
         : (void *)(addr))

#if defined(__TASKING__)
#define DCACHE_INV_LINE(p)  __asm volatile ("cachea.i [%0]0" : : "a"(p) : "memory")
#else
#define DCACHE_INV_LINE(p)  __asm__ volatile ("cachea.i [%0]0" : : "a"(p) : "memory")
#endif

/* Invalidate (no write-back) the data cache lines covering [addr, addr+len).
 * Only used on RX DMA buffers, which the CPU never writes through the cached
 * view, so discarding the lines can never lose data. */
static void geth_dcache_invalidate(const uint8 *addr, uint32 len)
{
    uint32 p   = (uint32)addr & ~31u;
    uint32 end = ((uint32)addr + len + 31u) & ~31u;

    for (; p < end; p += 32)
    {
        DCACHE_INV_LINE(p);
    }
}

/* Helper: check if an Ethernet frame contains a TCP segment suitable for TSO.
 * Uses lwIP protocol structs (already included via netif/etharp.h). */
static boolean is_tcp_segment(const uint8_t *frame, uint16_t len)
{
    struct eth_hdr *eth;
    struct ip_hdr  *iph;

    if (len < (SIZEOF_ETH_HDR + IP_HLEN))
        return FALSE;

    eth = (struct eth_hdr *)frame;
    if (htons(eth->type) != ETHTYPE_IP)
        return FALSE;

    iph = (struct ip_hdr *)(frame + SIZEOF_ETH_HDR);
    if (IPH_PROTO(iph) != 6)  /* IP_PROTO_TCP */
        return FALSE;

    return TRUE;
}
#include "Ifx_Netif.h"
#include "IfxGeth_Phy_Rtl8211f.h"
#include "Configuration.h"
#include <string.h>

/* Define those to better describe your network interface. */
#define IFNAME0 'e'
#define IFNAME1 'n'

/* ---- 802.3x flow control tuning (override from CMake if needed) ----
 * The MTL RX FIFO is 8KB. RFA/RFD select the fill levels at which the MAC
 * emits XOFF / XON pause frames:
 *   pause  when free space <  (RFA+1) * 0.5KB + 0.5KB
 *   resume when free space >  (RFD+1) * 0.5KB + 0.5KB
 * GETH_FC_PAUSE_TIME is in 512-bit-time quanta (0x10 = 8.2us @1Gbps).
 * Keep it SHORT: an over-long XOFF throttles the link far below line rate
 * even though the FIFO has already drained. */
#ifndef GETH_FC_ENABLE
#define GETH_FC_ENABLE      1
#endif
#ifndef GETH_FC_RFA
#define GETH_FC_RFA         1
#endif
#ifndef GETH_FC_RFD
#define GETH_FC_RFD         4
#endif
#ifndef GETH_FC_PAUSE_TIME
#define GETH_FC_PAUSE_TIME  0x1000u
#endif

/* Diagnostic counters (read via UDP diag service, port 5002) */
volatile uint32 g_diag_rx_ok    = 0;  /* frames delivered to lwIP */
volatile uint32 g_diag_rx_err   = 0;  /* frames dropped: descriptor error */
volatile uint32 g_diag_rx_nobuf = 0;  /* frames dropped: pbuf_alloc failed */
volatile uint32 g_diag_tx_pkts  = 0;  /* frames handed to TX DMA */

/* Cycle-level profiling (STM ticks, read via UDP diag service) */
#include "IfxStm.h"
volatile uint32 g_prof_copy_ticks  = 0; /* RX: memcpy out of DMA buffer  */
volatile uint32 g_prof_copy_cnt    = 0;
volatile uint32 g_prof_input_ticks = 0; /* lwIP stack processing (netif->input) */
volatile uint32 g_prof_input_cnt   = 0;
volatile uint32 g_prof_tx_ticks    = 0; /* TX: total low_level_output    */
volatile uint32 g_prof_tx_cnt      = 0;
volatile uint32 g_prof_alloc_ticks = 0; /* RX: pbuf_alloc(PBUF_POOL)     */
#define PROF_NOW()  IfxStm_getLower(&MODULE_STM0)

/**
 * Helper struct to hold private data used to operate your ethernet interface.
 * Keeping the ethernet address of the MAC in this struct is not necessary
 * as it is already kept in the struct netif.
 * But this is only an example, anyway...
 */
struct ethernetif
{
    eth_addr_t *ethaddr;
    /* Add whatever per-interface state that is needed here. */
};

/* pin configuration RTL8211F */
const IfxGeth_Eth_RgmiiPins rtl8211f_pins = {
                                   .txClk = &ETH_TXCLK_PIN,     /* TXCLK */
                                   .txd0 = &ETH_TXD0_PIN,       /* TXD0 */
                                   .txd1 = &ETH_TXD1_PIN,       /* TXD1 */
                                   .txd2 = &ETH_TXD2_PIN,       /* TXD2 */
                                   .txd3 = &ETH_TXD3_PIN,       /* TXD3 */
		                           .txCtl = &ETH_TXCTL_PIN,     /* TXCTL */
		                           .rxClk = &ETH_RXCLK_PIN,     /* RXCLK */
                                   .rxd0 = &ETH_RXD0_PIN,       /* RXD0 */
								   .rxd1 = &ETH_RXD1_PIN,       /* RXD1 */
								   .rxd2 = &ETH_RXD2_PIN,       /* RXD2 */
								   .rxd3 = &ETH_RXD3_PIN,       /* RXD3 */
								   .rxCtl = &ETH_RXCTL_PIN,     /* RXCTL */
                                   .mdc = &ETH_MDC_PIN,         /* MDC */
                                   .mdio = &ETH_MDIO_PIN,       /* MDIO */
		                           .grefClk = &ETH_GREFCLK_PIN  /* GREFCLK */
};

/**
 * In this function, the hardware should be initialized.
 * Called from ethernetif_init().
 *
 * @param netif the already initialized lwip network interface structure
 *        for this ethernetif
 */
static void low_level_init(netif_t *netif)
{
    IfxGeth_Eth *ethernetif = netif->state;
    int     i;

    /* set MAC hardware address length */
    netif->hwaddr_len = ETHARP_HWADDR_LEN;

    /* set MAC hardware address */
    for (i = 0; i < ETHARP_HWADDR_LEN; i++)
    {
        netif->hwaddr[i] = g_Lwip.eth_addr.addr[i];
    }

    /* maximum transfer unit */
    netif->mtu = 1500;

    /* device capabilities */
    /* don't set NETIF_FLAG_ETHARP if this device is not an ethernet one */
    /* we don't set the LINK_UP flag because we don't say when it is linked */
    netif->flags = NETIF_FLAG_BROADCAST | NETIF_FLAG_ETHARP;

    /* Do whatever else is needed to initialize interface. */
    {
        IfxGeth_Eth_Config GethConfig;

        IfxGeth_Eth_initModuleConfig(&GethConfig, &MODULE_GETH);
        // this is our RTL8211F
        GethConfig.phyInterfaceMode = IfxGeth_PhyInterfaceMode_rgmii;
        GethConfig.pins.rgmiiPins = &rtl8211f_pins;
        GethConfig.mac.lineSpeed = IfxGeth_LineSpeed_1000Mbps;
        // MAC core configuration
        GethConfig.mac.loopbackMode = IfxGeth_LoopbackMode_disable;
        GethConfig.mac.macAddress[0] = netif->hwaddr[0];
        GethConfig.mac.macAddress[1] = netif->hwaddr[1];
        GethConfig.mac.macAddress[2] = netif->hwaddr[2];
        GethConfig.mac.macAddress[3] = netif->hwaddr[3];
        GethConfig.mac.macAddress[4] = netif->hwaddr[4];
        GethConfig.mac.macAddress[5] = netif->hwaddr[5];

        // MTL configuration
    GethConfig.mtl.numOfTxQueues = 1;
    GethConfig.mtl.numOfRxQueues = 1;
    GethConfig.mtl.txQueue[0].txQueueSize = IfxGeth_QueueSize_8192Bytes;
    GethConfig.mtl.txQueue[0].storeAndForward = TRUE;
    GethConfig.mtl.rxQueue[0].rxQueueSize = IfxGeth_QueueSize_8192Bytes;
        GethConfig.mtl.rxQueue[0].rxDmaChannelMap = IfxGeth_RxDmaChannel_0;
        GethConfig.mtl.rxQueue[0].storeAndForward = TRUE;

        GethConfig.dma.numOfTxChannels = 1;
        GethConfig.dma.numOfRxChannels = 1;
    /* NOTE: FB=1 (fixed burst, per Infineon gigabit appnote) locks up the
     * GETH DMA on this board with LMU-based buffers - verified with FB+MB,
     * FB alone, FB+PBLX8 and runtime writes. Keep AAL+MB and use PBLX8
     * instead to lengthen bursts. */
    GethConfig.dma.addressAlignedBeatsEnabled = TRUE;
    GethConfig.dma.fixedBurstEnabled = FALSE;
    GethConfig.dma.mixedBurstEnabled = TRUE;
        /* NOTE: descriptor lists and DMA buffers are passed via the LMU
         * non-cached view (0xB...) so CPU accesses bypass the data cache
         * and stay coherent with the GETH DMA. */
        GethConfig.dma.txChannel[0].channelId = IfxGeth_TxDmaChannel_0;
        GethConfig.dma.txChannel[0].txDescrList = (IfxGeth_TxDescrList *)GETH_DMA_ADDR(&lmu_txDescrList[0]);
        GethConfig.dma.txChannel[0].txBuffer1StartAddress = (uint32 *)GETH_DMA_ADDR(&channel0TxBuffer1[0][0]); // user buffer
    GethConfig.dma.txChannel[0].txBuffer1Size = IFXGETH_MAX_TX_BUFFER_SIZE; // used to calculate the next descriptor  buffer offset
    GethConfig.dma.txChannel[0].maxBurstLength = IfxGeth_DmaBurstLength_32;
    GethConfig.dma.txChannel[0].enableOSF = TRUE;

        GethConfig.dma.rxChannel[0].channelId = IfxGeth_RxDmaChannel_0;
        GethConfig.dma.rxChannel[0].rxDescrList = (IfxGeth_RxDescrList *)GETH_DMA_ADDR(&lmu_rxDescrList[0]);
        GethConfig.dma.rxChannel[0].rxBuffer1StartAddress = (uint32 *)GETH_DMA_ADDR(&channel0RxBuffer1[0][0]); // user buffer
    GethConfig.dma.rxChannel[0].rxBuffer1Size = IFXGETH_MAX_RX_BUFFER_SIZE; // user defined variable
    GethConfig.dma.rxChannel[0].maxBurstLength = IfxGeth_DmaBurstLength_32;

        IfxSrc_Tos gethIsrProvider;

        if (CPU_WHICH_SERVICE_ETHERNET) gethIsrProvider = (IfxSrc_Tos)(CPU_WHICH_SERVICE_ETHERNET+1);
        else  gethIsrProvider = (IfxSrc_Tos)CPU_WHICH_SERVICE_ETHERNET;

        GethConfig.dma.txInterrupt[0].channelId = IfxGeth_DmaChannel_0;
        GethConfig.dma.txInterrupt[0].priority = ISR_PRIORITY_GETH_TX;    // priority
        GethConfig.dma.txInterrupt[0].provider = gethIsrProvider;
        GethConfig.dma.rxInterrupt[0].channelId = IfxGeth_DmaChannel_0;
        GethConfig.dma.rxInterrupt[0].priority = ISR_PRIORITY_GETH_RX;    // priority
        GethConfig.dma.rxInterrupt[0].provider = gethIsrProvider;

    	/* first we reset our phy manually, to make sure that the phy is ready when we init our module */
        {
            /* Raise fGETH from the iLLD default 150MHz (GETHDIV=2) to
             * 300MHz (GETHDIV=1, synchronous to fSRI/fSOURCE0). The GETH
             * kernel clock feeds the DMA/MTL engines; at 150MHz the RX DMA
             * drain rate capped iperf at ~730Mbps (with PBLX8) even though
             * the CPU was idle. At 300MHz the board sustains ~945Mbps
             * (TCP theoretical max for 1460-byte MSS on GigE) with zero
             * FIFO overflows and zero PAUSE frames. */
            {
                extern float32 IfxScuCcu_setGethFrequency(float32 gethFreq);
                IfxScuCcu_setGethFrequency(300000000.0f);
            }
        	IfxGeth_enableModule(&MODULE_GETH);
        	IfxPort_setPinModeOutput(ETH_MDC_PIN.pin.port, ETH_MDC_PIN.pin.pinIndex, IfxPort_OutputMode_pushPull, ETH_MDC_PIN.select);
            GETH_GPCTL.B.ALTI0  = ETH_MDIO_PIN.inSelect;

            while (GETH_MAC_MDIO_ADDRESS.B.GB) {};
            // first we wait that we are able to communicate with the Phy
            do
            {
            	GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) | (3 << 2) | (1 << 0);
                while (GETH_MAC_MDIO_ADDRESS.B.GB) {};
            } while (GETH_MAC_MDIO_DATA.U & 0x8000);                                                      // wait for reset to finish
            // reset PHY
            // put data
        	GETH_MAC_MDIO_DATA.U = 0x8000;
            GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) |  (1 << 2) | (1 << 0);
            while (GETH_MAC_MDIO_ADDRESS.B.GB) {};

            do
            {
            	GETH_MAC_MDIO_ADDRESS.U = (0 << 21) | (0 << 16) | (0 << 8) | (3 << 2) | (1 << 0);
                while (GETH_MAC_MDIO_ADDRESS.B.GB) {};
            } while (GETH_MAC_MDIO_DATA.U & 0x8000);                                                      // wait for reset to finish
        }

        // initialize the module
    	IfxGeth_Eth_initModule(ethernetif, &GethConfig);

        /* 802.3x hardware flow control: pause the sender before the 8KB MTL
         * RX FIFO overflows (line-rate bursts exceed the drain rate).
         *  - EHFC: enable hardware flow control based on FIFO fill level
         *  - RFA=2: send PAUSE when fill >= 8KB - (1 + 2*0.5)KB = 6KB
         *           (2KB headroom = ~16us at 1Gbps covers pause reaction time)
         *  - RFD=6: release when fill <= 8KB - (1 + 6*0.5)KB = 4KB
         *  - PT=0x1000: moderate pause quanta (~2ms); the MAC sends a
         *    zero-quanta pause when fill drops below RFD, so the link
         *    resumes as soon as the FIFO drains. PLT=4: re-send early. */
        GETH_MTL_RXQ0_OPERATION_MODE.B.EHFC = GETH_FC_ENABLE;
        GETH_MTL_RXQ0_OPERATION_MODE.B.RFA  = GETH_FC_RFA;
        GETH_MTL_RXQ0_OPERATION_MODE.B.RFD  = GETH_FC_RFD;
#if GETH_FC_ENABLE
        GETH_MAC_Q0_TX_FLOW_CTRL.U = ((uint32)GETH_FC_PAUSE_TIME << 16) | (4u << 4) | (1u << 1);
#else
        GETH_MAC_Q0_TX_FLOW_CTRL.U = 0;
#endif

        /* DMA burst tuning: with plain PBL=32 (128B bursts) the RX DMA tops
         * out at ~620Mbps while the MTL FIFO overflows and the CPU idles,
         * i.e. the per-SRI-transaction latency dominates. PBLX8 multiplies
         * the programmed PBL by 8. NOTE: PBLX8 must NOT be combined with
         * FB=1 (256-beat fixed bursts lock up the SRI/AHB bridge). */
#ifndef GETH_DMA_PBLX8
#define GETH_DMA_PBLX8      1
#endif
#ifndef GETH_DMA_RXPBL
#define GETH_DMA_RXPBL      32
#endif
#ifndef GETH_DMA_TXPBL
#define GETH_DMA_TXPBL      32
#endif
        GETH_DMA_CH0_CONTROL.B.PBLX8    = GETH_DMA_PBLX8;
        GETH_DMA_CH0_RX_CONTROL.B.RXPBL = GETH_DMA_RXPBL;
        GETH_DMA_CH0_TX_CONTROL.B.TXPBL = GETH_DMA_TXPBL;

   		IfxGeth_Eth_Phy_Rtl8211f_init();

    	// and enable transmitter/receiver
    	IfxGeth_Eth_startTransmitters(ethernetif, 1);
    	IfxGeth_Eth_startReceivers(ethernetif, 1);

        /* Pure polling data path: the main loop drains the RX ring at full
         * speed, so per-packet RX/TX DMA interrupts (80k+/s at 600Mbps) are
         * pure overhead. Disable both the DMA interrupt generation and the
         * SRC service request nodes. All error conditions are polled. */
        GETH_DMA_CH0_INTERRUPT_ENABLE.U = 0;
        IfxSrc_disable(IfxGeth_getSrcPointer(&MODULE_GETH, IfxGeth_ServiceRequest_2)); /* TX ch0 */
        IfxSrc_disable(IfxGeth_getSrcPointer(&MODULE_GETH, IfxGeth_ServiceRequest_6)); /* RX ch0 */

    	// The ETH is ready for use now!
        /* we set the LINK_UP flag if we have a valid link */
    	if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSTS == 1)
    	{
    		// we have a valid link
    		netif->flags |= NETIF_FLAG_LINK_UP;
    		// we set the correct duplexMode
    		if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKMOD == 1)
    			IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_fullDuplex);
    		else
    			IfxGeth_mac_setDuplexMode(ethernetif->gethSFR, IfxGeth_DuplexMode_halfDuplex);
    		// we set the correct speed
    		if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSPEED == 0)
    			// 10MBit speed
    			IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_10Mbps);
    		else
        		if (GETH_MAC_PHYIF_CONTROL_STATUS.B.LNKSPEED == 1)
        			// 100MBit speed
        			IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_100Mbps);
        		else
        			// 1000MBit speed
        			IfxGeth_mac_setLineSpeed(ethernetif->gethSFR, IfxGeth_LineSpeed_1000Mbps);
    	}
    }
}

/**
 * This function should do the actual transmission of the packet. The packet is
 * contained in the pbuf that is passed to the function. This pbuf
 * might be chained.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @param p the MAC packet to send (e.g. IP packet including MAC addresses and type)
 * @return ERR_OK if the packet could be sent
 *         an err_t value if the packet couldn't be sent
 *
 * @note Returning ERR_MEM here if a DMA queue of your MAC is full can lead to
 *       strange results. You might consider waiting for space in the DMA queue
 *       to become availale since the stack doesn't retry to send a packet
 *       dropped because of memory failure (except for the TCP timers).
 */
static err_t low_level_output(netif_t *netif, pbuf_t *p)
{
    IfxGeth_Eth *ethernetif = netif->state;
    struct pbuf *q;
    u16_t length = p->tot_len;
    uint32 prof_t0 = PROF_NOW();
    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output (p=%#x)\n", p));

    /* TSO path only for genuinely oversized TCP segments (payload > MSS).
     * Standard lwIP segments (<= MSS payload, frame <= 1514) always take the
     * normal path: single copy + full HW checksum insertion (CIC_TPL=3). */
    if ((length > (TCP_MSS + SIZEOF_ETH_HDR + 40)) &&
        (p->len >= (SIZEOF_ETH_HDR + 20)) &&
        is_tcp_segment((uint8 *)p->payload, p->len))
    {
            volatile IfxGeth_TxDescr *ctxDesc;
            volatile IfxGeth_TxDescr *dataDesc;
            volatile IfxGeth_TxDescr *nextDescr;
            uint32  remaining, offset, chunk;
            uint8  *src;
            u16_t   l = length;

            /* Single copy: pbuf chain directly into TSO scratch buffer
             * (LMU non-cached view for DMA coherency). */
            uint8 *tso_dst = (uint8 *)GETH_DMA_ADDR(tso_tx_buffer);
            u16_t  off     = 0;
            for (q = p; q != NULL; q = q->next)
            {
                memcpy(&tso_dst[off], q->payload, q->len);
                off = off + q->len;
            }

            /* Context descriptor: provides MSS for TSO hardware */
            ctxDesc = IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
            ctxDesc->TDES3.U         = 0;
            ctxDesc->TDES3.C.TCMSSV  = 1;
            ctxDesc->TDES3.C.CTXT    = 1;
            ctxDesc->TDES3.C.OWN     = 1;
            ctxDesc->TDES2.U         = 0;
            ctxDesc->TDES2.C.MSS     = TCP_MSS;
            ctxDesc->TDES0.U         = 0;
            IfxGeth_Eth_shuffleTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);

            /* Data descriptors: chain through the large TSO buffer.
             * Each descriptor points to a chunk of up to bufferLength bytes. */
            remaining = l;
            offset    = 0;
            src       = tso_dst;
            {
                uint32 bufferLength = ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txBuf1Size;
                uint32 numOfDesc    = remaining / bufferLength;
                if (remaining % bufferLength) numOfDesc++;
                uint32 di;
                for (di = 0; di < numOfDesc; di++)
                {
                    dataDesc = IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
                    chunk = (remaining > bufferLength) ? bufferLength : remaining;

                    dataDesc->TDES0.U     = (uint32)(src + offset);
                    dataDesc->TDES2.R.B1L = chunk;
                    dataDesc->TDES2.R.IOC = (di == (numOfDesc - 1)) ? 1 : 0;
                    dataDesc->TDES3.U     = 0;
                    if (di == 0)
                    {
                        dataDesc->TDES3.R.FL_TPL = l;  /* total frame length on first desc */
                    }
                    dataDesc->TDES3.R.TSE     = 1;
                    dataDesc->TDES3.R.CIC_TPL = 2;
                    dataDesc->TDES3.R.SAIC    = 0;
                    dataDesc->TDES3.R.CPC     = 0;
                    dataDesc->TDES3.R.FD      = (di == 0) ? 1 : 0;
                    dataDesc->TDES3.R.LD      = (di == (numOfDesc - 1)) ? 1 : 0;
                    dataDesc->TDES3.R.CTXT    = 0;
                    dataDesc->TDES3.R.OWN     = 1;

                    offset    += chunk;
                    remaining -= chunk;
                    IfxGeth_Eth_shuffleTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
                }
                nextDescr = IfxGeth_Eth_getActualTxDescriptor(ethernetif, IfxGeth_TxDmaChannel_0);
            }

            /* Trigger DMA transmission */
            IfxGeth_dma_setTxDescriptorTailPointer(ethernetif->gethSFR, IfxGeth_TxDmaChannel_0, (uint32)nextDescr);
            IfxGeth_Eth_wakeupTransmitter(ethernetif, IfxGeth_TxDmaChannel_0);
            ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txCount++;
            ethernetif->txChannel[IfxGeth_TxDmaChannel_0].txDescrPtr = nextDescr;
    }
    else
    {
        /* Normal path: single copy into the descriptor's DMA buffer, then
         * send with full HW checksum insertion (CIC_TPL=3, set in
         * IfxGeth_Eth_sendTransmitBuffer). */
        u8_t *tbuf = IfxGeth_Eth_waitTransmitBuffer(ethernetif, IfxGeth_TxDmaChannel_0);
        u16_t l    = 0;

        for (q = p; q != NULL; q = q->next)
        {
            memcpy((u8_t *)&tbuf[l], q->payload, q->len);
            l = l + q->len;
            LWIP_ASSERT("low_level_output: length overflow the buffer\n", (l <= IFXGETH_MAX_TX_BUFFER_SIZE));
        }

        IfxGeth_Eth_sendTransmitBuffer(ethernetif, l, IfxGeth_TxDmaChannel_0);
    }

    g_diag_tx_pkts++;
    g_prof_tx_ticks += (PROF_NOW() - prof_t0);
    g_prof_tx_cnt++;
    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("low_level_output: signal length: %d\n", length));
    LINK_STATS_INC(link.xmit);
    return ERR_OK;
}

static uint16 GetRxFrameSize(IfxGeth_RxDescr *descr)
{
  uint16 len;

  uint32 rdes3 = descr->RDES3.U;
  uint32 rdes1 = descr->RDES1.U;

  /* Drop on: ES (error summary), IPCE (payload checksum error), or
   * !LD (multi-buffer frame). Mirrors the original Infineon port.
   * RX COE (MAC_CONFIGURATION.IPC) is intentionally NOT enabled, and the
   * IPHE bit is intentionally NOT used for dropping: with COE off the MAC
   * does not compute these flags, so leaving them out avoids spurious drops. */
  if (((rdes3 & (1UL << 15)) != 0U) ||
      ((rdes1 & (1UL << 7)) != 0U) ||
      ((rdes3 & (1UL << 28)) == 0U))
  {
    /* Error, this block is invalid */
    len = 0xFFFFU;
  }
  else
  {
    /* Subtract CRC */
    len = (uint16)((rdes3 & 0x7FFF) - 4U);
  }

  return len;
}

/**
 * Should allocate a pbuf and transfer the bytes of the incoming
 * packet from the interface into the pbuf.
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return a pbuf filled with the received packet (including MAC header)
 *         NULL on memory error
 */
static pbuf_t *low_level_input(netif_t *netif)
{
    IfxGeth_Eth *ethernetif = netif->state;
    pbuf_t *p;
    pbuf_t *q;
    u16_t   len;

    len = 0;
    if (IfxGeth_Eth_isRxDataAvailable(ethernetif, IfxGeth_RxDmaChannel_0) != FALSE)
    {
        len = GetRxFrameSize((IfxGeth_RxDescr *)IfxGeth_Eth_getActualRxDescriptor(ethernetif, IfxGeth_RxDmaChannel_0));
    }

    if (len == 0)
    {
        return NULL;
    }

    /* Error frame — release DMA buffer and return NULL */
    if (len == 0xFFFFU)
    {
        g_diag_rx_err++;
        IfxGeth_Eth_freeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);
        return NULL;
    }

    /* Copy-based RX: allocate a pbuf from the pool and memcpy the frame out of
     * the DMA buffer. This is the safe, proven approach for NO_SYS + TCP, which
     * keeps references to received pbufs (retransmits, window) — giving the DMA
     * buffer back to hardware while the stack still references it would corrupt
     * data. The DMA buffer is released immediately after the copy. */
    uint32 ta = PROF_NOW();
    p = pbuf_alloc(PBUF_RAW, len, PBUF_POOL);
    g_prof_alloc_ticks += (PROF_NOW() - ta);

    if (p != NULL)
    {
        uint8 *buffer = IfxGeth_Eth_getReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);
        /* The driver hands out the non-cached alias. Read the payload through
         * the cached view so the copy uses burst line fills, after discarding
         * the stale lines the DMA just wrote behind the cache's back. */
        uint8 *cbuf   = (uint8 *)GETH_CACHED_ADDR(buffer);
        u16_t  l      = 0;
        uint32 t0     = PROF_NOW();

        geth_dcache_invalidate(cbuf, len);

        for (q = p; q != NULL; q = q->next)
        {
            memcpy((u8_t *)q->payload, (u8_t *)&cbuf[l], q->len);
            l = l + q->len;
        }

        g_prof_copy_ticks += (PROF_NOW() - t0);
        g_prof_copy_cnt++;

        LINK_STATS_INC(link.recv);
        g_diag_rx_ok++;
    }
    else
    {
        /* Out of pool pbufs — drop the frame and free the DMA buffer. */
        LINK_STATS_INC(link.memerr);
        LINK_STATS_INC(link.drop);
        g_diag_rx_nobuf++;
    }

    /* Frame copied; release the DMA buffer back to hardware right away. */
    IfxGeth_Eth_freeReceiveBuffer(ethernetif, IfxGeth_RxDmaChannel_0);

    return p;
}


/**
 * This function should be called when a packet is ready to be read
 * from the interface. It uses the function low_level_input() that
 * should handle the actual reception of bytes from the network
 * interface. Then the type of the received packet is determined and
 * the appropriate input function is called.
 *
 * @param netif the lwip network interface structure for this ethernetif
 */
err_t ifx_netif_input(netif_t *netif)
{
    IfxGeth_Eth *ethernetif = netif->state;
    eth_hdr_t *ethhdr;
    pbuf_t    *p;

    /* move received packet into a new pbuf */
    p = low_level_input(netif);

    /* no packet could be read, silently ignore this */
    if (p == NULL)
    {
        return ERR_OK;
    }

    /* points to packet payload, which starts with an Ethernet header */
    ethhdr = p->payload;

    switch (htons(ethhdr->type))
    {
    /* IP or ARP packet? */
    case ETHTYPE_IP:
    case ETHTYPE_ARP:
#if PPPOE_SUPPORT
    case ETHTYPE_PPPOEDISC:
    case ETHTYPE_PPPOE:
#endif /* PPPOE_SUPPORT */
        /* full packet send to tcpip_thread to process */
        {
            uint32 t0 = PROF_NOW();
            if (netif->input(p, netif) != ERR_OK)
            {
                LWIP_DEBUGF(NETIF_DEBUG, ("ifx_netif_input: IP input error\n"));
                pbuf_free(p);
            }
            g_prof_input_ticks += (PROF_NOW() - t0);
            g_prof_input_cnt++;
        }
        break;

    default:
        LWIP_DEBUGF(NETIF_DEBUG, ("ifx_netif_input: type unknown\n"));
        pbuf_free(p);
        break;
    }

    /* NOTE: the DMA buffer was already released inside low_level_input()
     * (after the frame was copied into a pool pbuf). Do NOT release it
     * again here — that would hand the same descriptor back to the GETH
     * DMA twice and corrupt the ring. */

    return ERR_OK;
}


/**
 * Should be called at the beginning of the program to set up the
 * network interface. It calls the function low_level_init() to do the
 * actual setup of the hardware.
 *
 * This function should be passed as a parameter to netif_add().
 *
 * @param netif the lwip network interface structure for this ethernetif
 * @return ERR_OK if the loopif is initialized
 *         ERR_MEM if private data couldn't be allocated
 *         any other err_t on error
 */
err_t ifx_netif_init(netif_t *netif)
{
    IfxGeth_Eth *ethernetif;

    LWIP_ASSERT("netif != NULL", (netif != NULL));
    LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE, ("ifx_netif_init ( %#x)\n", netif));

    ethernetif = IfxGeth_get();

    if (ethernetif == NULL)
    {
        LWIP_DEBUGF(NETIF_DEBUG, ("ifx_netif_init: out of memory\n"));
        return ERR_MEM;
    }

#if LWIP_NETIF_HOSTNAME
    /* Initialize interface hostname */
    netif->hostname = "lwip";
#endif /* LWIP_NETIF_HOSTNAME */

    /*
     * Initialize the snmp variables and counters inside the struct netif.
     * The last argument should be replaced with your link speed, in units
     * of bits per second.
     */
    //NETIF_INIT_SNMP(netif, snmp_ifType_ethernet_csmacd, LINK_SPEED_OF_YOUR_NETIF_IN_BPS);

    netif->state      = ethernetif;
    netif->name[0]    = IFNAME0;
    netif->name[1]    = IFNAME1;
    /* We directly use etharp_output() here to save a function call.
     * You can instead declare your own function an call etharp_output()
     * from it if you have to do some checks before sending (e.g. if link
     * is available...) */
    netif->output     = etharp_output;
    netif->linkoutput = low_level_output;

    /* initialize the hardware */
    low_level_init(netif);

    return ERR_OK;
}
